components/patient-data/impl/pom.xml, components/patient-data/impl/src/main/java/org/phenotips/data/internal/controller/SolvedController.java, components/patient-data/impl/src/main/resources/META-INF/components.txt
Includes:
- Issue #1534: pubmed id
- Issue #1535: solved status
- Issue #1536: resolution notes
- Issue #1540: solved gene symbol
Would have added tests but I couldn't see any example of testing a PatientDataController class, and the tests that were there seemed misconfigured with my Eclipse environment. :/
=> Added "solved" data controller

components/patient-data/ui/src/main/resources/PhenoTips/PatientSheetCode.xml, components/patient-data/ui/src/main/resources/PhenoTips/PatientSheetMacros.xml, components/patient-data/ui/src/main/resources/PhenoTips/UIX_Field__charts.xml, components/patient-data/ui/src/main/resources/PhenoTips/UIX_Field__omim_suggestions.xml, components/patient-data/ui/src/main/resources/PhenoTips/UIX_Field__phenotype.xml
=> Issue #1492: Expand/collapse all should be made more visual

components/ontology-access/hpo/ui/src/main/resources/PhenoTips/HPOBranchDisplayer.xml
=> Issue #1486: Clarify hierarchy structure of inheritance terms

components/widgets/ui/src/main/resources/PhenoTips/Widgets.xml
=> Issue #1389: "Arrow should not be shown for leaf terms in ontology browser"

components/widgets/ui/src/main/resources/PhenoTips/Widgets.xml
Changing double space to single
=> Issue #1389: "Arrow should not be shown for leaf terms in ontology browser

components/export/api/pom.xml, components/export/api/src/main/java/org/phenotips/export/internal/DataToCellConverter.java, components/patient-data/impl/src/main/java/org/phenotips/data/internal/controller/GlobalQualifiersController.java
=> Issue #1612 "Mode of inheritance" is no longer exported in the Excel file

components/widgets/ui/src/main/resources/PhenoTips/Widgets.xml
=> Issue #1572: Navigating by tab from the month of birth to the day takes two tabs

components/patient-data/impl/pom.xml, components/patient-data/impl/src/main/java/org/phenotips/data/internal/controller/APGARController.java, components/patient-data/impl/src/main/java/org/phenotips/data/internal/controller/AbstractSimpleController.java, components/patient-data/impl/src/main/java/org/phenotips/data/internal/controller/ClinicalStatusController.java, components/patient-data/impl/src/main/java/org/phenotips/data/internal/controller/DatesController.java, components/patient-data/impl/src/main/java/org/phenotips/data/internal/controller/GlobalQualifiersController.java, components/patient-data/impl/src/main/java/org/phenotips/data/internal/controller/IdentifiersController.java, components/patient-data/impl/src/main/java/org/phenotips/data/internal/controller/MetaDataController.java, components/patient-data/impl/src/main/java/org/phenotips/data/internal/controller/RejectedGeneListController.java, components/patient-data/impl/src/main/java/org/phenotips/data/internal/controller/VersionsController.java, components/patient-data/impl/src/main/resources/META-INF/components.txt
=> Issue #1531: "Patient toJSON() should include more fields"

components/vocabularies/ethnicity/api/src/main/java/org/phenotips/vocabulary/internal/solr/EthnicityOntology.java, components/vocabularies/hgnc/api/src/test/java/org/phenotips/vocabulary/internal/GeneNomenclatureTest.java
Changed a few small errors so the tests pass
=> fixed javadoc mistake and error return status value

components/skin/ui/src/main/resources/PhenoTips/ContentTopMenu.xml
Fixed: exporting from patient document page
=> issue #1591: PDF/JSON is opened in a new tab

components/patient-data/ui/src/main/resources/PhenoTips/PatientSheetCode.xml
=> Issue #1549 Suggest dialogs should hide when they loose focus

components/export/api/src/main/java/org/phenotips/export/internal/DataToCellConverter.java, components/patient-data/impl/src/main/java/org/phenotips/data/internal/controller/PrenatalPerinatalHistoryController.java, components/patient-data/ui/src/main/resources/PhenoTips/PatientClass.xml, components/patient-data/ui/src/main/resources/PhenoTips/PatientTemplate.xml, components/patient-data/ui/src/main/resources/PhenoTips/UIX_Field__assisted_reproduction.xml
Question added. Property added to patient data export
=> Issue #1655: New 'Assisted reproduction' questions: donor sperm or egg

components/patient-data-sharing/push-ui/src/main/resources/PhenoTips/PushPatient.xml, components/patient-data/impl/src/main/java/org/phenotips/data/internal/controller/SexController.java, components/patient-data/impl/src/main/resources/ApplicationResources.properties, components/patient-data/pageobjects/src/main/java/org/phenotips/data/test/po/PatientRecordEditPage.java, components/patient-data/ui/src/main/resources/PhenoTips/PatientClass.xml, components/patient-measurements/api/src/main/resources/ApplicationResources.properties, components/pedigree/resources/src/main/resources/pedigree/model/baseGraph.js, components/pedigree/resources/src/main/resources/pedigree/model/dynamicGraph.js, components/pedigree/resources/src/main/resources/pedigree/model/export.js, components/pedigree/resources/src/main/resources/pedigree/model/import.js, components/pedigree/resources/src/main/resources/pedigree/pedigree.js, components/pedigree/resources/src/main/resources/pedigree/view/abstractPerson.js, components/pedigree/resources/src/main/resources/pedigree/view/abstractPersonVisuals.js, components/pedigree/resources/src/main/resources/pedigree/view/nodetypeSelectionBubble.js, components/pedigree/resources/src/main/resources/pedigree/view/personVisuals.js
@allasm, @danielpgross, please review
=> Issue 1654#2

components/base-war/src/main/webapp/resources/js/scriptaculous/dragdrop.js, components/pedigree/resources/src/main/resources/pedigree/view.js, components/pedigree/resources/src/main/resources/pedigree/view/legend.js
Added onHover wrapper and modified dragdrop.js source file, now the event is passed to the onHover callback along with other arguments to get the coordinates of draggable object.
=> Issue #1723:Pedigree drag and drop UI needs better feedback. 

components/patient-data/impl/src/test/java/org/phenotips/data/internal/controller/ClinicalStatusControllerTest.java, components/patient-data/impl/src/test/java/org/phenotips/data/internal/controller/LifeStatusControllerTest.java, components/patient-data/impl/src/test/java/org/phenotips/data/internal/controller/SexControllerTest.java
Tests for PatientDataControllers that use SimpleValuePatientData
=> Issue #1274 simple value controllers

components/pedigree/resources/src/main/resources/pedigree/pedigree.js, components/pedigree/resources/src/main/resources/pedigree/view/person.js, components/pedigree/resources/src/main/resources/pedigree/view/personVisuals.js
=> Issue #1625: Display age of diagnosis for cancers

components/xwiki-translation-manager/pom.xml, components/xwiki-translation-manager/src/main/java/org/phenotips/translation/TranslationManager.java, components/xwiki-translation-manager/src/main/resources/components.txt
Added a utility class for translation messages key based on current locale.
=> translation-manager

components/pedigree/resources/src/main/resources/pedigree/editor.css, components/pedigree/resources/src/main/resources/pedigree/view/ageCalc.js, components/pedigree/resources/src/main/resources/pedigree/view/nodeMenu.js
...some rewordings, added "none of the above" button.
=> Issue #1859: Updated cancer section in the pedigree editor

components/patient-data/ui/src/main/resources/PhenoTips/PatientSheetCode.xml
=> PT-2049: Remove yellow on-hover row highlight of a table. 

components/pedigree/resources/src/main/resources/pedigree/pedigree.js
=> PT-2094: Modify button label on a Pedigree save dialog from DON'T QUIT to DON'T CLOSE

components/pedigree/resources/src/main/resources/pedigree/editor.css, components/pedigree/resources/src/main/resources/pedigree/model/helpers.js, components/pedigree/resources/src/main/resources/pedigree/pedigree.js, components/pedigree/resources/src/main/resources/pedigree/pedigreeDate.js, components/pedigree/resources/src/main/resources/pedigree/pedigreeEditorParameters.js, components/pedigree/resources/src/main/resources/pedigree/preferencesManager.js, components/pedigree/resources/src/main/resources/pedigree/saveLoadEngine.js, components/pedigree/resources/src/main/resources/pedigree/view.js, components/pedigree/resources/src/main/resources/pedigree/view/abstractHoverbox.js, components/pedigree/resources/src/main/resources/pedigree/view/abstractNodeVisuals.js, components/pedigree/resources/src/main/resources/pedigree/view/abstractPersonVisuals.js, components/pedigree/resources/src/main/resources/pedigree/view/datepicker.js, components/pedigree/resources/src/main/resources/pedigree/view/disorderLegend.js, components/pedigree/resources/src/main/resources/pedigree/view/nodeMenu.js, components/pedigree/resources/src/main/resources/pedigree/view/partnershipVisuals.js, components/pedigree/resources/src/main/resources/pedigree/view/personPlaceholderVisuals.js, components/pedigree/resources/src/main/resources/pedigree/view/personVisuals.js, components/pedigree/resources/src/main/resources/pedigree/view/printDialog.js, components/pedigree/resources/src/main/resources/pedigree/view/printEngine.js, components/pedigree/resources/src/main/resources/pedigree/view/svgWrapper.js, components/pedigree/resources/src/main/resources/pedigree/view/workspace.js, components/pedigree/ui/src/main/resources/PhenoTips/PedigreeGlobalSettings.xml, components/pedigree/ui/src/main/resources/PhenoTips/PedigreeInterface.xml
Also fixes visible editor-mode only symbols (e.g. node shading) visible in saved pedigree images.
=> Issue #1624: Added a pedigree print dialog/ability to print pedigrees.

components/pedigree/resources/src/main/resources/pedigree/controller.js, components/pedigree/resources/src/main/resources/pedigree/editor.css, components/pedigree/resources/src/main/resources/pedigree/model/dynamicGraph.js, components/pedigree/resources/src/main/resources/pedigree/model/export.js, components/pedigree/resources/src/main/resources/pedigree/model/helpers.js, components/pedigree/resources/src/main/resources/pedigree/model/import.js, components/pedigree/resources/src/main/resources/pedigree/model/positionedGraph.js, components/pedigree/resources/src/main/resources/pedigree/pedigree.js, components/pedigree/resources/src/main/resources/pedigree/saveLoadEngine.js, components/pedigree/resources/src/main/resources/pedigree/undoRedoManager.js, components/pedigree/resources/src/main/resources/pedigree/versionUpdater.js, components/pedigree/resources/src/main/resources/pedigree/view.js, components/pedigree/resources/src/main/resources/pedigree/view/abstractHoverbox.js, components/pedigree/resources/src/main/resources/pedigree/view/abstractPersonVisuals.js, components/pedigree/resources/src/main/resources/pedigree/view/cancersLegend.js, components/pedigree/resources/src/main/resources/pedigree/view/datepicker.js, components/pedigree/resources/src/main/resources/pedigree/view/disorderLegend.js, components/pedigree/resources/src/main/resources/pedigree/view/geneLegend.js, components/pedigree/resources/src/main/resources/pedigree/view/graphicHelpers.js, components/pedigree/resources/src/main/resources/pedigree/view/hpoLegend.js, components/pedigree/resources/src/main/resources/pedigree/view/legend.js, components/pedigree/resources/src/main/resources/pedigree/view/nodeMenu.js, components/pedigree/resources/src/main/resources/pedigree/view/person.js, components/pedigree/resources/src/main/resources/pedigree/view/personVisuals.js, components/pedigree/resources/src/main/resources/pedigree/view/workspace.js
Fixes/implementations for PT-1830, PT-2020, PT-2090, PT-2123, PT-2145,  PT-2152, PT-2162, PT-2165, PT-2166, PT-2185
=> Minor pedigree fixes

components/pedigree/resources/src/main/resources/pedigree/model/export.js, components/pedigree/resources/src/main/resources/pedigree/pedigreeDate.js
=> PT-2131: BOADICEA export incorrectly lists age of dead family members

components/patient-data/indexing/pom.xml, components/patient-data/indexing/src/test/java/org/phenotips/data/indexing/internal/PatientEventListenerTest.java, components/patient-data/indexing/src/test/java/org/phenotips/data/indexing/internal/SolrPatientIndexerTest.java
PR originally by @veronikaslc, patched by @buske
=> PT-2192: Tests for patient indexing

components/export/api/src/main/java/org/phenotips/export/internal/DataToCellConverter.java, components/ncbieutils-services/api/src/main/java/org/phenotips/ncbieutils/internal/AbstractSpecializedNCBIEUtilsAccessService.java, components/patient-access-rules/api/src/main/java/org/phenotips/data/permissions/internal/AbstractAccessLevel.java, components/patient-access-rules/api/src/main/java/org/phenotips/data/permissions/internal/AbstractVisibility.java, components/patient-access-rules/api/src/main/java/org/phenotips/data/permissions/internal/DefaultCollaborator.java, components/patient-data/impl/src/main/java/org/phenotips/data/internal/PhenoTipsPatientRepository.java, components/solr-access-service/api/src/main/java/org/phenotips/solr/OmimScriptService.java, components/vocabularies/api/src/main/java/org/phenotips/vocabulary/internal/solr/SolrVocabularyTerm.java, components/xwiki-platform-users/xwiki-platform-users-wiki/src/main/java/org/xwiki/users/internal/WikiUser.java
[UseCollectionIsEmpty](http://pmd.sourceforge.net/pmd-5.2.0/pmd-java/rules/java/design.html#UseCollectionIsEmpty): Collection.size() == 0 is O(N) if the collection is a linked list, whereas Collection.isEmpty() is always O(1) and it's also easier to read.
[SimplifyConditional](http://pmd.sourceforge.net/pmd-5.2.0/pmd-java/rules/java/design.html#SimplifyConditional): "null instanceof ClassName" always returns false (the null check is built in).
[AddEmptyString](http://pmd.sourceforge.net/pmd-5.2.0/pmd-java/rules/java/optimizations.html#AddEmptyString): Using "" with the + operator creates an extra string object unnecessarily.
=> More PMD optimizations

components/export/api/src/main/java/org/phenotips/export/internal/ConversionHelpers.java
Using an iterator is about 2x faster.
=> Remove items while iterating instead of saving them to remove later

components/skin/ui/src/main/resources/PhenoTips/ContentTopMenu.xml
Changed target="__blank" to target="_blank"
This looks like a typo. I fixed it with `find -type f | xargs sed -i "s/__blank/_blank/"`
=> PT-2272: Can't open two history windows at the same time

components/pedigree/resources/src/main/resources/pedigree/familyDataLoader.js
=> PT-2160: Move the modal with warning of sensitive information to the middle of the screen and add CLOSE button to it.

components/pedigree/resources/src/main/resources/pedigree/editor.css, components/pedigree/resources/src/main/resources/pedigree/view/nodeMenu.js
=> PT-2290: Cancer tab looks awkward once vertical scrollbar gets added.

components/pedigree/resources/src/main/resources/pedigree/model/import.js
=> PT-2331: Can't import PED files with comment lines

components/patient-data/impl/src/main/resources/ApplicationResources.properties, components/patient-data/ui/src/main/resources/PhenoTips/PatientConsent.xml
- Refactored HTML, CSS, JS to remove some redundancies and make class names clearer
- Updated translation strings
=> Refactored consent display

components/skin/ui/src/main/resources/PhenoTips/ContentTopMenu.xml
Do not ask user to save explicitly before export
=> [misc]: Autosave before export

components/patient-data/impl/src/checkstyle/checkstyle-suppressions.xml, components/patient-data/impl/src/main/java/org/phenotips/data/internal/PhenoTipsPatient.java
=> PT-2395: After push Prenatal and perinatal history items are listed under Clinical symptoms and physical findings.

components/patient-data-sharing/push-api/src/main/java/org/phenotips/data/push/internal/DefaultPushPatientData.java, components/patient-data-sharing/receiver-api/src/main/java/org/phenotips/data/receive/internal/DefaultReceivePatientData.java, components/patient-data/impl/src/main/java/org/phenotips/data/internal/controller/AbstractComplexController.java, components/patient-data/impl/src/main/java/org/phenotips/data/internal/controller/GeneListController.java, components/patient-data/impl/src/main/java/org/phenotips/data/internal/controller/ParentalAgeController.java, components/patient-data/impl/src/main/java/org/phenotips/data/internal/controller/PrenatalPerinatalHistoryController.java, components/patient-data/impl/src/main/java/org/phenotips/data/internal/controller/VariantListController.java, components/patient-data/impl/src/test/java/org/phenotips/data/internal/controller/GeneListControllerTest.java, components/patient-data/impl/src/test/java/org/phenotips/data/internal/controller/ParentalAgeControllerTest.java, components/patient-data/impl/src/test/java/org/phenotips/data/internal/controller/VariantListControllerTest.java
Fixing various bugs with controllers read/writeJSON() functionality.
=> [misc]: reformatting controllers

components/export/api/src/main/java/org/phenotips/export/internal/DataToCellConverter.java, components/patient-data/impl/src/main/java/org/phenotips/data/internal/controller/VariantListController.java, components/patient-data/impl/src/test/java/org/phenotips/data/internal/controller/VariantListControllerTest.java, components/patient-data/ui/src/main/resources/PhenoTips/GeneVariantClass.xml
=> [misc] Add new variant investigation dropdown item 'Investigation needed'

components/patient-data/ui/src/main/resources/PhenoTips/PatientClass.xml, components/patient-data/ui/src/main/resources/PhenoTips/UIX_Field__gender.xml
=> PT-2197: Unknown should be (default) option for Sex field.

components/widgets/ui/src/main/resources/PhenoTips/Widgets.xml
=> PT-2436: Phenotype sub terms should NOT expand when clicking on N

components/pedigree/resources/src/main/resources/pedigree/view/personVisuals.js
=> PT-2465: Anonymised pedigree should not show external ID, comments, names and DoB.

components/patient-data/impl/src/main/java/org/phenotips/data/internal/controller/AbstractComplexController.java
=> PT-2508: Push functionality should also push a free text. 

components/export/ui/src/main/resources/PhenoTips/ExportPreferences.xml, components/patient-data-sharing/push-ui/src/main/resources/PhenoTips/PushPatient.xml, components/widgets/resources/src/main/resources/resources/uicomponents/widgets/exportData.css, components/widgets/resources/src/main/resources/resources/uicomponents/widgets/exportData.js
=> PT-2509: Push dialog improvements.

components/widgets/resources/src/main/resources/templates/geneVariantMacros.vm
Poor alignment of '+' signs in Add variant and Add gene buttons
=> [misc] alignment of '+' signs in buttons of gene-variant section

components/default-settings/src/main/resources/XWiki/XWikiPreferences.xml, components/pedigree/resources/src/main/resources/pedigree/controller.js, components/pedigree/resources/src/main/resources/pedigree/editor.css, components/pedigree/resources/src/main/resources/pedigree/extensionManager.js, components/pedigree/resources/src/main/resources/pedigree/model/dynamicGraph.js, components/pedigree/resources/src/main/resources/pedigree/model/export.js, components/pedigree/resources/src/main/resources/pedigree/model/helpers.js, components/pedigree/resources/src/main/resources/pedigree/model/import.js, components/pedigree/resources/src/main/resources/pedigree/model/positionedGraph.js, components/pedigree/resources/src/main/resources/pedigree/nodeMenuFields.js, components/pedigree/resources/src/main/resources/pedigree/pedigree.js, components/pedigree/resources/src/main/resources/pedigree/pedigreeDate.js, components/pedigree/resources/src/main/resources/pedigree/pedigreeEditorParameters.js, components/pedigree/resources/src/main/resources/pedigree/saveLoadEngine.js, components/pedigree/resources/src/main/resources/pedigree/undoRedoManager.js, components/pedigree/resources/src/main/resources/pedigree/view.js, components/pedigree/resources/src/main/resources/pedigree/view/abstractNodeVisuals.js, components/pedigree/resources/src/main/resources/pedigree/view/ageCalc.js, components/pedigree/resources/src/main/resources/pedigree/view/childlessBehaviorVisuals.js, components/pedigree/resources/src/main/resources/pedigree/view/datepicker.js, components/pedigree/resources/src/main/resources/pedigree/view/nodeMenu.js, components/pedigree/resources/src/main/resources/pedigree/view/person.js, components/pedigree/resources/src/main/resources/pedigree/view/personVisuals.js, components/pedigree/resources/src/main/resources/pedigree/view/printDialog.js, components/pedigree/resources/src/main/resources/pedigree/view/printEngine.js, components/pedigree/resources/src/main/resources/pedigree/view/workspace.js, components/pedigree/ui/src/main/resources/PhenoTips/PedigreeConfiguration.xml, components/pedigree/ui/src/main/resources/PhenoTips/PedigreeGlobalSettings.xml, components/pedigree/ui/src/main/resources/PhenoTips/PedigreeInterface.xml, components/pedigree/ui/src/main/resources/PhenoTips/PedigreeSampleExtension.xml
@veronikaslc @danielpgross please review
=> Fixes for PT-2378, PT-2463, PT-2465, PT-2476, PT-2498, PT-2516

components/widgets/resources/src/main/resources/resources/uicomponents/widgets/extraGeneVariantData.js
=> [misc]: Correcting the left blue arrow pointing down when adding new variant.

components/export/ui/src/main/resources/PhenoTips/ExportPreferences.xml, components/patient-data-sharing/push-ui/src/main/resources/PhenoTips/PushPatient.xml, components/patient-data-sharing/receiver-ui/src/main/resources/data/ReceivePatientConfiguration.xml, components/patient-data/api/src/main/java/org/phenotips/data/Feature.java, components/patient-data/impl/pom.xml, components/patient-data/impl/src/checkstyle/checkstyle-suppressions.xml, components/patient-data/impl/src/main/java/org/phenotips/data/internal/NonStandardFeatureCategoryUpdater.java, components/patient-data/impl/src/main/java/org/phenotips/data/internal/PhenoTipsFeature.java, components/patient-data/impl/src/main/java/org/phenotips/data/internal/PhenoTipsFeatureMetadatum.java, components/patient-data/impl/src/main/java/org/phenotips/data/internal/PhenoTipsPatient.java, components/patient-data/impl/src/main/java/org/phenotips/data/internal/PhenoTipsPatientConsentManager.java, components/patient-data/impl/src/main/java/org/phenotips/data/internal/controller/APGARController.java, components/patient-data/impl/src/main/java/org/phenotips/data/internal/controller/AbstractComplexController.java, components/patient-data/impl/src/main/java/org/phenotips/data/internal/controller/PrenatalPerinatalHistoryController.java, components/patient-data/impl/src/main/resources/ApplicationResources.properties, components/patient-data/rest/src/main/java/org/phenotips/data/rest/internal/DefaultPatientResourceImpl.java, components/patient-data/rest/src/main/java/org/phenotips/data/rest/internal/DefaultPatientsResourceImpl.java, components/patient-data/rest/src/test/java/org/phenotips/data/rest/internal/DefaultPatientsResourceImplTest.java, components/specificity-meter/api/src/main/java/org/phenotips/data/script/PatientSpecificityScriptService.java, components/vocabularies/rest/src/main/java/org/phenotips/vocabularies/rest/internal/DefaultDomainObjectFactory.java, components/widgets/resources/src/main/resources/resources/uicomponents/widgets/exportData.css, components/widgets/resources/src/main/resources/resources/uicomponents/widgets/exportData.js, pom.xml
And a few other small push dialogue UI fixes
=> Fixes for PT-1933, PT-2445, PT-2452, PT-2457, PT-2484, PT-2530, PT-2561, PT-2562, PT-2568

components/patient-measurements/migrations/pom.xml, components/patient-measurements/migrations/src/checkstyle/checkstyle-suppressions.xml, components/patient-measurements/migrations/src/main/java/org/phenotips/measurements/internal/R71291PhenoTips1969DataMigration.java, components/patient-measurements/migrations/src/main/resources/META-INF/components.txt
=> PT-1969: Backend: Migrator from the old measurement data structure. 

components/widgets/resources/src/main/resources/resources/uicomponents/widgets/extraGeneVariantData.js
=> PT-2544: Labels for checkbox fields in the genes and variants section target the first gene/variant added.

components/patient-data/ui/src/main/resources/PhenoTips/PatientClass.xml, components/patient-data/ui/src/main/resources/PhenoTips/PatientTemplate.xml
=> PT-2161: Birth/death date "hidden" input fields are visible for a short time after opening patient edit page

components/application-configuration/api/src/main/java/org/phenotips/configuration/RecordSection.java, components/application-configuration/api/src/main/java/org/phenotips/configuration/internal/global/DefaultRecordSection.java, components/patient-data/ui/src/main/resources/PhenoTips/PatientSheet.xml, components/patient-data/ui/src/main/resources/PhenoTips/PatientSheetCode.xml, components/patient-data/ui/src/main/resources/PhenoTips/UIX_Section__patient-info.xml, pom.xml
Fixed. Added a "expanded_by_default" parameter to section configuration to make
configuring which sections are expanded by default easier. Also made the
expand-collapse JS extension load first, which visually speeds things up.
=> PT-2585: Make patient page more visually static and less annoying on load

components/patient-data/ui/src/main/resources/PhenoTips/UIX_Field__phenotype.xml
@marta- @danielpgross @allasm Please review. Thanks!
=> PT-1618: Quick Phenotype search section overlaps the topmost item

components/patient-data/migrations/src/main/java/org/phenotips/data/internal/R71490PhenoTips1280DataMigration.java
=> PT-2603: 1.2 to 1.3 gene migration adds one blank space before comment

components/patient-data/impl/src/main/java/org/phenotips/data/internal/controller/GeneListController.java
=> PT-2602: 1.3 code should also support the 1.2 JSON structure, where the rejected and candidate genes are in a different place.

components/patient-data/impl/src/main/java/org/phenotips/data/internal/controller/ClinicalStatusController.java, components/patient-data/impl/src/test/java/org/phenotips/data/internal/controller/ClinicalStatusControllerTest.java
=> PT-2612: Checkboxes This patient is clinically normal and Case solved should be pushed too.

components/patient-data/impl/src/main/java/org/phenotips/data/internal/EmptyGenotypeObjectsRemover.java, components/patient-data/impl/src/main/resources/META-INF/components.txt, components/patient-data/impl/src/test/java/org/phenotips/data/internal/EmptyGenotypeObjectsRemoverTest.java
=> [misc]: Remove empty genes and variants when patient saved.

components/pedigree/resources/src/main/resources/pedigree/model/dynamicGraph.js
=> PT-2607: After a twin is added some functionality is broken in pedigree editor

components/widgets/ui/src/main/resources/PhenoTips/Widgets.xml
A minimal code allowing to grab an icon from suggestions and display in the suggest list.
=> [misc] : Add icon option to the suggest widget dropdown list

components/export/api/src/main/java/org/phenotips/export/internal/DataToCellConverter.java
=> PT-2648: Support exporting of Clinically Normal status.

components/default-settings/src/main/resources/XWiki/XWikiPreferences.xml
This removes registration rights from guests and only allows Admins to create new accounts.
=> PT-2662: Disable self-registration

components/widgets/ui/src/main/resources/PhenoTips/Widgets.xml
Reusable confirmation box written by Sergiu
=> [misc] Create confirmation dialog initiated by visibility controller

components/security/authorization/src/main/java/org/phenotips/security/authorization/internal/XWikiACLAuthorizationModule.java, components/security/authorization/src/test/java/org/phenotips/security/authorization/internal/XWikiACLAuthorizationModuleTest.java
One of cases is when user is XWiki.XWikiGuest.
=> [misc] Checking user for being null.

components/widgets/ui/src/main/resources/PhenoTips/Widgets.xml
Sergiu's work. 
Please review: @danielpgross @josecv
=> [misc] Add ability to set extra classes for the free-multiselect widget

components/patient-data/api/src/main/java/org/phenotips/data/DictionaryPatientData.java, components/patient-data/api/src/main/java/org/phenotips/data/IndexedPatientData.java, components/patient-data/api/src/main/java/org/phenotips/data/PatientData.java, components/patient-data/api/src/main/java/org/phenotips/data/SimpleValuePatientData.java, pom.xml
@itaiGershtansky @veronikaslc please review
=> PT-2670: Improve PatientData interface

components/patient-data/migrations/src/main/java/org/phenotips/data/internal/R71495PhenoTips2711DataMigration.java, components/patient-data/migrations/src/main/resources/META-INF/components.txt, components/pedigree/resources/src/main/resources/pedigree/controller.js, components/pedigree/resources/src/main/resources/pedigree/model/dynamicGraph.js, components/pedigree/resources/src/main/resources/pedigree/model/export.js, components/pedigree/resources/src/main/resources/pedigree/model/import.js, components/pedigree/resources/src/main/resources/pedigree/nodeMenuFields.js, components/pedigree/resources/src/main/resources/pedigree/pedigree.js, components/pedigree/resources/src/main/resources/pedigree/view.js, components/pedigree/resources/src/main/resources/pedigree/view/candidateGeneLegend.js, components/pedigree/resources/src/main/resources/pedigree/view/causalGeneLegend.js, components/pedigree/resources/src/main/resources/pedigree/view/geneLegend.js, components/pedigree/resources/src/main/resources/pedigree/view/nodeMenu.js, components/pedigree/resources/src/main/resources/pedigree/view/person.js, components/pedigree/ui/src/main/resources/PhenoTips/PedigreeMacros.xml
@veronikaslc and @itaiGershtansky - please code review (typos found in first code review have been fixed)
@AlexLapena - please test, as discussed on Thursday
=> PT 2641: Better support for new genes in pedigree editor

components/navigation/ui/src/main/resources/PhenoTips/LiveTableResults.xml
Please review @marta @danielpgross 
Filtering number properties in the patients data table by specifying a min and max.
For task https://phenotips.atlassian.net/browse/NIAID-52.
Intended use example:
`// DatabaseFilters.xml`
`...`
`<input type="text" name="number_property/min" value="" />`
`<input type="text" name="number_property/max" value='" />`
`...`
=> Implemented filtering numbers by min/max in patients table

components/widgets/resources/src/main/resources/resources/uicomponents/PhenotypeSelectionUtils.js
Could @veronikaslc and @allasm review please?
=> Add the PhenotypeSelectionUtils module by @Gene42

components/pedigree/resources/src/main/resources/pedigree/view/nodeMenu.js, components/pedigree/resources/src/main/resources/pedigree/view/printEngine.js, components/pedigree/ui/src/main/resources/PhenoTips/PedigreeMacros.xml
Fixes PT-2754 & PT-2755
@AlexLapena has already tested both (posted in slack)
@veronikaslc - can you do a quick code review?
=> Pedigree fixes 1.3m2

components/patient-data/ui/src/main/resources/PhenoTips/PatientSheetCode.xml, components/skin/ui/src/main/resources/PhenoTips/Skin.xml
Better fix takes into account native xwiki suggest widget and works for both administration and patient form.
=> PT-2763: Suggest dialogs should hide when they lose focus.

components/widgets/resources/src/main/resources/resources/uicomponents/widgets/extraGeneVariantData.css
=> PT-2749: Comments box is truncated when variant is added to a gene

components/skin/ui/src/main/resources/PhenoTips/ContentTopMenu.xml
@buske @itaiGershtansky Please review.
=> PT-2787: adjusted top menu fonts to ensure that all buttons match

components/widgets/ui/src/main/resources/PhenoTips/ImageDisplayer.xml
@veronikaslc @allasm please review
=> [misc] Extend file uploader to be useable in unsaved/fake objects

components/pedigree/ui/src/main/resources/PhenoTips/UIX_Field__pedigree.xml
=> PT-2826: Change cursor for pedigree thumbnail to arrow if user has only view rights

components/pedigree/resources/src/main/resources/pedigree/nodeMenuFields.js
For consistency with Genotype information section in patient form
=> [misc] Pedigree Genotype label change from 'rejected' to 'negative'

components/family-studies/api/src/main/java/org/phenotips/studies/family/internal/PedigreeProcessorImpl.java, components/patient-data/api/pom.xml, components/patient-data/api/src/main/java/org/phenotips/data/PhenoTipsDate.java, components/patient-data/impl/src/main/java/org/phenotips/data/internal/controller/LifeStatusController.java
=> PT-2818: Life status does not transfer correctly from pedigree to patient records.

components/base-war/src/main/java/org/xwiki/velocity/tools/JSONTool.java
@veronikaslc @itaiGershtansky please review
=> PT-2808: Implemented parseToJSONObject and parseToJSONArray

components/pedigree/resources/src/main/resources/pedigree/controller.js, components/pedigree/resources/src/main/resources/pedigree/model/dynamicGraph.js, components/pedigree/resources/src/main/resources/pedigree/model/edgeOptimization.js, components/pedigree/resources/src/main/resources/pedigree/model/import.js, components/pedigree/resources/src/main/resources/pedigree/model/ordering.js, components/pedigree/resources/src/main/resources/pedigree/pedigree.js, components/pedigree/resources/src/main/resources/pedigree/view.js, components/pedigree/resources/src/main/resources/pedigree/view/personHoverbox.js, components/pedigree/resources/src/main/resources/pedigree/view/workspace.js
@allasm @sdumitriu Fixes the "from" typo.
=> Fixing typos

components/pedigree/resources/src/main/resources/pedigree/view/nodeMenu.js
=> PT-2789: Pressing 'None of the above..' button doesn't clear 'As of' drop down value.

components/patient-data/rest/pom.xml, components/patient-data/rest/src/checkstyle/checkstyle-suppressions.xml, components/patient-data/rest/src/main/java/org/phenotips/data/rest/PatientsResource.java, components/patient-data/rest/src/main/java/org/phenotips/data/rest/internal/DefaultPatientsResourceImpl.java, components/patient-data/rest/src/test/java/org/phenotips/data/rest/internal/DefaultPatientsResourceImplTest.java, pom.xml
@itaiGershtansky @veronikaslc please review.
=> PT-2807: added functionality for creating multiple patients from their json representation

components/pedigree/resources/src/main/resources/pedigree/externalEndpoints.js, components/pedigree/resources/src/main/resources/pedigree/filesaver/FileSaver.js, components/pedigree/resources/src/main/resources/pedigree/view/exportSelector.js, components/pedigree/ui/src/main/resources/PhenoTips/PedigreeImageService.xml
=> PT-2230: Allow exporting pedigree as an image from within pedigree editor.

components/pedigree/resources/src/main/resources/pedigree/editor.css, components/pedigree/resources/src/main/resources/pedigree/model/export.js, components/pedigree/resources/src/main/resources/pedigree/view/disorderLegend.js, components/pedigree/resources/src/main/resources/pedigree/view/exportSelector.js, components/pedigree/resources/src/main/resources/pedigree/view/hpoLegend.js, components/pedigree/resources/src/main/resources/pedigree/view/legend.js, components/pedigree/resources/src/main/resources/pedigree/view/printDialog.js, components/pedigree/resources/src/main/resources/pedigree/view/workspace.js
Added phenotypes, cancers, genes
=> PT-2723: Users should be able to select what traits are reflected in the affected column when exporting the PED file of a pedigree

components/widgets/resources/src/main/resources/resources/uicomponents/widgets/exportData.css
=> PT-2870: Delete dialog looks incomplete on Mac (chrome, safari)

components/export/api/src/main/java/org/phenotips/export/internal/DataToCellConverter.java, components/export/api/src/main/resources/ApplicationResources.properties, components/export/api/src/main/resources/ApplicationResources_es.properties
PT-2906, PT-2907, PT-2908, PT-2909, PT-2910, PT-2911 and PT-2914.
=> Various Excel fixes

components/widgets/resources/src/main/resources/resources/uicomponents/widgets/extraGeneVariantData.js, components/widgets/resources/src/main/resources/templates/geneVariantMacros.vm
@sdumitriu @marta- Broken variant fix. Please review.
=> PT-2785: Broken variants -- fixed

components/patient-data/ui/src/main/resources/PhenoTips/PatientSheetCode.xml
=> PT-2712: Phenotype Selector Bug when using Browse Related Terms

components/base-war/src/main/webapp/skins/phenotips/language.vm, components/skin/ui/src/main/resources/PhenoTips/Skin.xml
=> PT-2913: Only the lower half of the logo in the header is clickable

components/patient-data/ui/src/main/resources/PhenoTips/PatientSheetCode.xml, components/skin/ui/src/main/resources/PhenoTips/Skin.xml
=> [bugfix] Small UI fix: the global tools menu entries are misaligned vertically

components/export/api/src/main/java/org/phenotips/export/internal/DataToCellConverter.java, components/export/api/src/main/resources/ApplicationResources.properties, components/export/ui/src/main/resources/PhenoTips/ExportPreferences.xml, components/patient-data/impl/src/main/java/org/phenotips/data/internal/controller/VariantListController.java, components/patient-data/impl/src/main/resources/ApplicationResources.properties, components/patient-data/impl/src/test/java/org/phenotips/data/internal/controller/VariantListControllerTest.java, components/patient-data/ui/src/main/resources/PhenoTips/GeneVariantClass.xml, components/patient-data/ui/src/main/resources/PhenoTips/UIX_Field__gene-variants.xml, components/widgets/resources/src/main/resources/resources/uicomponents/widgets/extraGeneVariantData.js, components/widgets/resources/src/main/resources/templates/geneVariantMacros.vm
=> PT-2883: Add chromosome, start position, end position and reference genome as fields for variants.

components/patient-data/api/src/main/resources/ApplicationResources.properties, components/patient-data/ui/src/main/resources/PhenoTips/JSONImportDialog.xml, components/skin/api/src/main/resources/ApplicationResources.properties, components/skin/ui/src/main/resources/PhenoTips/ContentTopMenu.xml
@marta- @sdumitriu Please review.
=> PT-2472: Added the Import JSON option to the action menu.

components/base-war/src/main/webapp/templates/commentsinline.vm, components/patient-data/ui/src/main/resources/PhenoTips/AllergiesDataClass.xml, components/patient-data/ui/src/main/resources/PhenoTips/GeneClass.xml, components/patient-data/ui/src/main/resources/PhenoTips/PatientClass.xml, components/patient-data/ui/src/main/resources/PhenoTips/PatientSheetCode.xml, components/patient-data/ui/src/main/resources/PhenoTips/PatientSheetMacros.xml, components/patient-data/ui/src/main/resources/PhenoTips/PatientTemplate.xml, components/patient-data/ui/src/main/resources/PhenoTips/RelativeClass.xml, components/patient-data/ui/src/main/resources/PhenoTips/UIX_Field__additional-images-exported.xml, components/patient-data/ui/src/main/resources/PhenoTips/UIX_Field__patient_name.xml, components/skin/ui/src/main/resources/PhenoTips/Skin.xml, components/widgets/resources/src/main/resources/templates/geneVariantMacros.vm, components/widgets/ui/src/main/resources/PhenoTips/TabelarDataMacros.xml
Fixed as well as other fields affected by the same problem
@sashaandjic @allasm This affects almost all the patient record form, please test thoroughly.
=> PT-1787: Using two consecutive dashes -- in the patient's identifier field will display it striked out in view mode

components/patient-data/ui/src/main/resources/PhenoTips/AllergiesDataClass.xml, components/patient-data/ui/src/main/resources/PhenoTips/PatientClass.xml, components/patient-data/ui/src/main/resources/PhenoTips/PatientTemplate.xml
=> PT-2967: Entering ethnicities or allergies with a pipe | in them will actually split the value in two

components/patient-data/ui/src/main/resources/PhenoTips/PatientSheetCode.xml, components/patient-data/ui/src/main/resources/PhenoTips/UIX_Field__omim_suggestions.xml
=> PT-2976: Show OMIM diagnosis suggestions in view mode

components/widgets/resources/src/main/resources/resources/uicomponents/widgets/geneVariantValidation.js
=> [misc] No validation of hidden inputs

components/patient-data/impl/src/main/java/org/phenotips/data/internal/controller/GlobalQualifiersController.java, components/patient-data/impl/src/test/java/org/phenotips/data/internal/controller/GlobalQualifiersControllerTest.java
=> PT-2980: Global mode of inheritance and Global age of onset cannot be pushed / imported

components/widgets/ui/src/main/resources/PhenoTips/Widgets.xml
@sashaandjic @marta- please review.
=> PT-2984: Fixed tabbing out of gene field if the correct gene is entered.

components/patient-data/ui/src/main/resources/PhenoTips/PatientClass.xml, components/patient-data/ui/src/main/resources/PhenoTips/PatientTemplate.xml, components/pedigree/ui/src/main/resources/PhenoTips/PedigreeMacros.xml, components/vocabularies/hpo/ui/src/main/resources/PhenoTips/PhenotypeMappingPreview.xml
=> PT-2996: Updated JSONTool usage in velocity code.

components/vocabularies/rest/src/main/java/org/phenotips/vocabularies/rest/VocabularyTermResource.java, components/vocabularies/rest/src/main/java/org/phenotips/vocabularies/rest/VocabularyTermSuggestionsResource.java
Tested all vocabulary rest resources, they seem to work fine. I didn't find any internal usages.
=> PT-3099: Modified the vocabularies REST API paths.

components/family-studies/api/src/main/java/org/phenotips/studies/family/internal/PedigreeProcessorImpl.java, components/pedigree/resources/src/main/resources/pedigree/controller.js, components/pedigree/resources/src/main/resources/pedigree/model/dynamicGraph.js, components/pedigree/resources/src/main/resources/pedigree/model/import.js, components/pedigree/resources/src/main/resources/pedigree/nodeMenuFields.js, components/pedigree/resources/src/main/resources/pedigree/pedigree.js, components/pedigree/resources/src/main/resources/pedigree/pedigreeEditorParameters.js, components/pedigree/resources/src/main/resources/pedigree/saveLoadEngine.js, components/pedigree/resources/src/main/resources/pedigree/view/importSelector.js, components/pedigree/resources/src/main/resources/pedigree/view/nodeMenu.js, components/pedigree/resources/src/main/resources/pedigree/view/nodetypeSelectionBubble.js, components/pedigree/resources/src/main/resources/pedigree/view/okCancelDialogue.js, components/pedigree/resources/src/main/resources/pedigree/view/patientDropLegend.js, components/pedigree/resources/src/main/resources/pedigree/view/printDialog.js, components/pedigree/resources/src/main/resources/pedigree/view/printEngine.js, components/pedigree/resources/src/main/resources/pedigree/view/templateSelector.js
Eliminating the upper bound for both number of persons in a group and number of twins.
=> PT-2291, PT-2954, PT-3012, PT-3014, PT-3016, PT-3103: Minor pedigree fixes

components/gene-panels/api/pom.xml, components/gene-panels/api/src/main/java/org/phenotips/panels/GenePanel.java, components/gene-panels/api/src/main/java/org/phenotips/panels/GenePanelFactory.java, components/gene-panels/api/src/main/java/org/phenotips/panels/TermsForGene.java, components/gene-panels/api/src/main/java/org/phenotips/panels/internal/DefaultGenePanelFactoryImpl.java, components/gene-panels/api/src/main/java/org/phenotips/panels/internal/DefaultGenePanelImpl.java, components/gene-panels/api/src/main/java/org/phenotips/panels/internal/DefaultTermsForGeneImpl.java, components/gene-panels/api/src/main/java/org/phenotips/panels/internal/TermsForGeneBuilder.java, components/gene-panels/api/src/main/resources/ApplicationResources.properties, components/gene-panels/api/src/main/resources/ApplicationResources_es.properties, components/gene-panels/api/src/main/resources/META-INF/components.txt, components/gene-panels/api/src/test/java/org/phenotips/panels/internal/DefaultGenePanelFactoryImplTest.java, components/gene-panels/api/src/test/java/org/phenotips/panels/internal/DefaultGenePanelImplTest.java, components/gene-panels/rest/pom.xml, components/gene-panels/rest/src/main/java/org/phenotips/panels/rest/GenePanelsPatientResource.java, components/gene-panels/rest/src/main/java/org/phenotips/panels/rest/GenePanelsResource.java, components/gene-panels/rest/src/main/java/org/phenotips/panels/rest/internal/DefaultGenePanelLoader.java, components/gene-panels/rest/src/main/java/org/phenotips/panels/rest/internal/DefaultGenePanelsPatientResourceImpl.java, components/gene-panels/rest/src/main/java/org/phenotips/panels/rest/internal/DefaultGenePanelsResourceImpl.java, components/gene-panels/rest/src/main/java/org/phenotips/panels/rest/internal/GenePanelLoader.java, components/gene-panels/rest/src/test/java/org/phenotips/panels/rest/internal/DefaultGenePanelLoaderTest.java, components/gene-panels/rest/src/test/java/org/phenotips/panels/rest/internal/DefaultGenePanelsResourceImplTest.java, components/gene-panels/ui/src/main/resources/PhenoTips/PanelsDisplay.xml, components/gene-panels/ui/src/main/resources/PhenoTips/PanelsExport.xml, components/patient-data/ui/src/main/resources/PhenoTips/PatientSheetCode.xml
Addressed all comments, with the exception of switching over to XWiki look for pagination. Will address that as a separate issue.
=> PT-3063: Gene panels code cleanup

components/family-studies/api/src/main/java/org/phenotips/studies/family/internal/export/FamilySearchResult.java, components/family-studies/api/src/main/java/org/phenotips/studies/family/internal/export/PhenotipsFamilyExport.java, components/family-studies/api/src/main/java/org/phenotips/studies/family/script/FamilyScriptService.java
Plus some variable naming and documentation fixes.
=> Family search should return at most the requested number of unique results

components/patient-data/ui/src/main/resources/PhenoTips/PatientSheetCode.xml
=> PT-3124: Invisible comments for negative phenotypes

components/family-studies/ui/src/main/resources/PhenoTips/FamilySelector.xml
.When "Add to an existing family" button is chosen, move the focus to Family name field.
=> PT-2536: Assign patient to the family modal improvement

components/pedigree/resources/src/main/resources/pedigree/controller.js, components/pedigree/resources/src/main/resources/pedigree/model/positionedGraph.js, components/pedigree/resources/src/main/resources/pedigree/pedigree.js, components/pedigree/resources/src/main/resources/pedigree/view/personVisuals.js
(discussing now if PT-3130 should also be included)
=> PT-3129 and PT-3132

components/pedigree/resources/src/main/resources/pedigree/view/personHoverbox.js
=> PT-2965: Minor correction in language used in pedigree editor

components/skin/ui/src/main/resources/ColorThemes/Maple leaf.xml
The newly Create and Browse menu had the wrong color.
=> [misc] Improved the styling of the Maple leaf color theme

components/family-studies/migrations/pom.xml, components/family-studies/migrations/src/checkstyle/checkstyle-suppressions.xml, components/family-studies/migrations/src/main/java/org/phenotips/studies/family/migrations/PhenotipsFamilyMigrations.java, components/family-studies/migrations/src/main/java/org/phenotips/studies/family/migrations/R71498PhenoTips2155DataMigration.java
- allow more patients in a family to have relatives
- migrates more complicated families
- links patients to existing pedigrees by external ID
=> PT 3183 - improved migrator for old family studies

components/family-studies/migrations/src/main/java/org/phenotips/studies/family/migrations/PhenotipsFamilyMigrations.java, components/family-studies/migrations/src/main/java/org/phenotips/studies/family/migrations/R71497PhenoTips2154DataMigration.java, components/family-studies/migrations/src/main/java/org/phenotips/studies/family/migrations/R71498PhenoTips2155DataMigration.java, components/patient-data/impl/src/main/resources/ApplicationResources.properties, components/patient-data/impl/src/main/resources/ApplicationResources_fr.properties, components/patient-data/migrations/src/main/java/org/phenotips/data/internal/R71490PhenoTips1280DataMigration.java, components/patient-data/migrations/src/main/java/org/phenotips/data/internal/R71501PhenoTips2991DataMigration.java, components/patient-data/ui/src/main/resources/PhenoTips/UIX_Field__family.xml, components/pedigree/ui/src/main/resources/PhenoTips/PedigreeMacros.xml
@sashaandjic please test
@veronikaslc please review my part of the code
=> Fixed migrations from 1.2.x and patient removal from families

components/navigation/ui/src/main/resources/data/AllData.xml, components/studies/ui/src/main/resources/PhenoTips/StudyCases.xml, components/users/ui/src/main/resources/PhenoTips/GroupCases.xml
Also made links consistent with how they're now displayed in data/AllData
=> PT-3200: Family reference column is displayed incorrectly on Study pages

components/pedigree/resources/src/main/resources/pedigree/model/dynamicGraph.js, components/pedigree/resources/src/main/resources/pedigree/model/export.js
Note: both commits need to be merged into `stable-1.3.x` before closing the pull request
=> PT-3208 and PT-3235

components/patient-data/ui/src/main/resources/PhenoTips/JSONImportDialog.xml
Fixed as per @sdumitriu suggestion.
=> PT-3261: Fixed multi-patient import through "Import JSON" option.

components/export/api/src/main/java/org/phenotips/export/internal/ConversionHelpers.java, components/export/api/src/main/java/org/phenotips/export/internal/DataToCellConverter.java, components/export/api/src/main/resources/ApplicationResources.properties, components/export/api/src/test/java/org/phenotips/export/internal/ConversionHelpersTest.java, components/export/ui/src/main/resources/PhenoTips/ExportPreferences.xml
Removes unnecessary options within JSON and Excel export options.
=> PT-3240 Remove Export Redundancies

components/widgets/resources/src/main/resources/templates/geneVariantMacros.vm
Authored with @veronikaslc and @allasm
=> PT-3223: Render translated values of variant properties

components/export/ui/src/main/resources/PhenoTips/ExportPreferences.xml
@sashaandjic Could you test this please?
=> PT-3276 Merge APGAR scores in push dialog

components/export/ui/src/main/resources/PhenoTips/ExportPreferences.xml, components/family-studies/api/src/main/java/org/phenotips/studies/family/internal/export/PhenotipsFamilyExport.java, components/patient-data/impl/pom.xml, components/patient-data/impl/src/main/java/org/phenotips/data/internal/controller/MedicalReportsController.java, components/patient-data/impl/src/main/java/org/phenotips/data/internal/controller/MedicalReportsLinksController.java, components/patient-data/impl/src/main/resources/META-INF/components.txt, components/patient-data/impl/src/test/java/org/phenotips/data/internal/controller/MedicalReportsControllerTest.java
=> PT-3282: Allow pushing/exporting/importing medical reports

components/studies/ui/src/main/resources/PhenoTips/StudyCases.xml, components/users/ui/src/main/resources/PhenoTips/GroupCases.xml, components/users/ui/src/main/resources/PhenoTips/GroupSharedCases.xml
=> PT-3284: Suggest widgets for vocabularies do not work on the filters for groups' owned and shared cases tables, and for study cases

components/pedigree/resources/src/main/resources/pedigree/view/person.js
=> PT-3272: Upon deletion of a pedigree node, its carrier genes are still present in the legend

components/pedigree/resources/src/main/resources/pedigree/nodeMenuFields.js, components/pedigree/resources/src/main/resources/pedigree/view/disorderLegend.js, components/pedigree/resources/src/main/resources/pedigree/view/legend.js
(both are simple text changes)
=> PT-3248 and PT-3275

components/application-configuration/api/pom.xml, components/application-configuration/migrations/pom.xml, components/base-war/pom.xml, components/default-settings/pom.xml, components/export/api/pom.xml, components/family-studies/migrations/pom.xml, components/gene-panels/api/pom.xml, components/gene-panels/rest/pom.xml, components/patient-access-rules/api/pom.xml, components/patient-access-rules/rest/pom.xml, components/patient-contacts/pom.xml, components/patient-data-extra/medication/api/pom.xml, components/patient-data/impl/pom.xml, components/patient-data/rest/pom.xml, components/patient-tools/pom.xml, components/security/bridge/pom.xml, components/specificity-meter/api/pom.xml, components/users/api/pom.xml, components/utilities/component-registry/pom.xml, components/vocabularies/api/pom.xml, components/vocabularies/ethnicity/api/pom.xml, components/vocabularies/hpo/annotations/pom.xml, components/vocabularies/omim/api/pom.xml, components/vocabularies/ordo/api/pom.xml, distribution/pom.xml, pom.xml, resources/ui/pom.xml
Done
Also fixed existing dependency issues
=> PT-3328: Fail the build if there are dependency misconfigurations

components/family-studies/migrations/src/main/java/org/phenotips/studies/family/migrations/R71503PhenoTips1393DataMigration.java, components/family-studies/migrations/src/main/resources/META-INF/components.txt, components/pedigree/resources/src/main/resources/pedigree/disorder.js, components/pedigree/resources/src/main/resources/pedigree/editor.css, components/pedigree/resources/src/main/resources/pedigree/gene.js, components/pedigree/resources/src/main/resources/pedigree/hpoTerm.js, components/pedigree/resources/src/main/resources/pedigree/model/helpers.js, components/pedigree/resources/src/main/resources/pedigree/pedigreeEditorParameters.js, components/pedigree/resources/src/main/resources/pedigree/preferencesManager.js, components/pedigree/resources/src/main/resources/pedigree/view.js, components/pedigree/resources/src/main/resources/pedigree/view/cancersLegend.js, components/pedigree/resources/src/main/resources/pedigree/view/causalGeneLegend.js, components/pedigree/resources/src/main/resources/pedigree/view/disorderLegend.js, components/pedigree/resources/src/main/resources/pedigree/view/geneLegend.js, components/pedigree/resources/src/main/resources/pedigree/view/hpoLegend.js, components/pedigree/resources/src/main/resources/pedigree/view/legend.js, components/pedigree/resources/src/main/resources/pedigree/view/person.js, components/pedigree/ui/src/main/resources/PhenoTips/PedigreeMacros.xml
@sashaandjic please test, @veronikaslc please review
Before merging we need to discuss default colouring for phenotypes (minor point, but wrong colours can be annoying)
=> PT-1393: Improve pedigree node colouring and legend

components/widgets/resources/src/main/resources/resources/uicomponents/widgets/extraGeneVariantData.css, components/widgets/resources/src/main/resources/templates/geneVariantMacros.vm
=> PT-3319: Long custom entries in the genes table cause layout issues

components/pedigree/resources/src/main/resources/pedigree/editor.css, components/pedigree/resources/src/main/resources/pedigree/pedigree.js, components/pedigree/resources/src/main/resources/pedigree/view/legend.js, components/pedigree/resources/src/main/resources/pedigree/view/person.js, components/pedigree/resources/src/main/resources/pedigree/view/personHoverbox.js
Done. @veronikaslc please review, @sashaandjic please test
=> PT-3286: When hovering an individual in the pedigree, highlight all its abnormalities/annotations in the legend

components/export/api/src/main/java/org/phenotips/export/internal/DataToCellConverter.java, components/export/api/src/main/resources/ApplicationResources.properties, components/export/ui/src/main/resources/PhenoTips/ExportPreferences.xml, components/patient-data/ui/src/main/resources/PhenoTips/UIX_Field__phenotype.xml, components/patient-data/ui/src/main/resources/PhenoTips/UIX_Field__prenatal_phenotype.xml
Things to test be tested: Push and Export (Excel & JSON), especially variants. This is important to be tested with permissions as well.
=> PT-3262 Improve the look of the export dialog

components/patient-access-rules/ui/src/main/resources/PhenoTips/PatientAccessRightsManagement.xml
Also fixes: PT-2933: Rights are not always correctly reflected on the patient form after they were edited. PT-2092: Unable to remove collaborator after modifying owner. Fixes UI error problem of: PT-3257:  Problem when user removes self as managing collaborator.
=> PT-3210: Refactor the patient permissions UIX to use the RESTful API for permissions. 

components/patient-data/api/src/main/resources/ApplicationResources.properties, components/pedigree/resources/src/main/resources/pedigree/editor.css, components/pedigree/resources/src/main/resources/pedigree/view/importSelector.js
This also redesigns the dialogue so that the file selection is similar to patient JSON import.
=> PT-3127: Rearrange pedigree import dialog to put the options above the actual file selection

components/family-studies/ui/src/main/resources/PhenoTips/FamilySelector.xml, components/patient-data-sharing/push-ui/src/main/resources/PhenoTips/PushPatient.xml, components/patient-data/ui/src/main/resources/PhenoTips/JSONImportDialog.xml, components/patient-data/ui/src/main/resources/PhenoTips/PatientConsent.xml, components/pedigree/ui/src/main/resources/PhenoTips/PedigreeSampleExtension.xml, components/widgets/resources/src/main/resources/resources/uicomponents/widgets/geneVariantValidation.js, components/widgets/ui/src/main/resources/PhenoTips/Widgets.xml, components/widgets/ui/src/main/resources/XWiki/DateTimePicker.xml
Added test that console exists before all function calls from console (with the exception of the pedigree component, where console is redefined if missing).
=> PT-3355: Some functionality is broken in IE9 (most notably pedigree editor can not be opened)

components/pedigree/resources/src/main/resources/pedigree/editor.css, components/pedigree/resources/src/main/resources/pedigree/model/helpers.js, components/pedigree/resources/src/main/resources/pedigree/view/abstractHoverbox.js, components/pedigree/resources/src/main/resources/pedigree/view/partnershipHoverbox.js, components/pedigree/resources/src/main/resources/pedigree/view/personHoverbox.js
=> PT-3320: Pedigree node hover boxes do not fade out when they should in some cases

components/family-studies/api/src/main/java/org/phenotips/studies/family/internal/PhenotipsFamilyRepository.java, components/patient-data/impl/src/main/java/org/phenotips/data/internal/PhenoTipsPatient.java
=> PT-2815: Family updates and patient JSON updates should be performed under the correct user

distribution/rpm/pom.xml, distribution/rpm/src/main/resources/ctakes.xml, distribution/standalone/pom.xml, distribution/standalone/src/assemble/application.xml, pom.xml, resources/jetty/packaging/src/main/resources/jetty/contexts/ctakes.xml, resources/ui/pom.xml
Integrated CTAKES, see PT-3358
=> PT-2496: Extract HPO terms from "Indication for referral" and "Medical history" and display them as phenotype suggestions

components/family-studies/api/src/main/java/org/phenotips/studies/family/internal/PhenotipsFamilyRepository.java
Fixed - @sashaandjic please test
=> PT-3385: Unauthenticated users can't save new pedigree

components/navigation/ui/src/main/resources/PhenoTips/DBWebHomeSheet.xml
To test, look at families directories and all patients table.
=> PT-3395: Improve the look of the livetable actions

components/family-studies/api/pom.xml, components/family-studies/api/src/main/java/org/phenotips/studies/family/internal/PedigreeProcessorImpl.java, components/patient-data/impl/src/main/resources/ApplicationResources.properties, components/patient-data/ui/src/main/resources/PhenoTips/PatientClass.xml, components/patient-data/ui/src/main/resources/PhenoTips/PatientSheetCode.xml, components/pedigree/resources/src/main/resources/pedigree/model/dynamicGraph.js
[PT-3458](https://github.com/phenotips/phenotips/pull/2462)
[PT-3459](https://github.com/phenotips/phenotips/pull/2463)
[PT-3461](https://github.com/phenotips/phenotips/pull/2465)
[PT-3462](https://github.com/phenotips/phenotips/pull/2466)
=> PT-3452 (PT-3458, PT-3459, PT-3461, PT-3462): Free-text diagnoses are no longer supported in the pedigree [fixed]

components/patient-data/ui/src/main/resources/PhenoTips/UIX_Field__gene-variants.xml, components/pedigree/resources/src/main/resources/pedigree/view/nodeMenu.js, components/widgets/ui/src/main/resources/PhenoTips/Widgets.xml
@sashaandjic: need to test patient form and pedigree editor
One way to test is to export patient to JSON (after all modification) and see what kind of ID gets recorded there
=> PT-3467: Genes should be stored internally as Ensembl IDs, not HGNC IDs

components/pedigree/ui/src/main/resources/PhenoTips/PedigreeMacros.xml
=> PT-3505: Delete pedigree button label is white in some cases

components/vocabularies/api/src/main/java/org/phenotips/vocabulary/internal/solr/AbstractSolrVocabulary.java
..when getLanguagePreference adding Spanish HPO extension to query
=> [bug] XWiki throws null pointer exception 

components/entity-access-rules/api/pom.xml, components/entity-access-rules/api/src/main/java/org/phenotips/data/permissions/Collaborator.java, components/entity-access-rules/api/src/main/java/org/phenotips/data/permissions/EntityAccess.java, components/entity-access-rules/api/src/main/java/org/phenotips/data/permissions/EntityPermissionsManager.java, components/entity-access-rules/api/src/main/java/org/phenotips/data/permissions/Owner.java, components/entity-access-rules/api/src/main/java/org/phenotips/data/permissions/Visibility.java, components/entity-access-rules/api/src/main/java/org/phenotips/data/permissions/internal/AbstractAccessLevel.java, components/entity-access-rules/api/src/main/java/org/phenotips/data/permissions/internal/AbstractVisibility.java, components/entity-access-rules/api/src/main/java/org/phenotips/data/permissions/internal/DefaultCollaborator.java, components/entity-access-rules/api/src/main/java/org/phenotips/data/permissions/internal/DefaultEntityAccess.java, components/entity-access-rules/api/src/main/java/org/phenotips/data/permissions/internal/DefaultEntityAccessHelper.java, components/entity-access-rules/api/src/main/java/org/phenotips/data/permissions/internal/DefaultEntityAccessManager.java, components/entity-access-rules/api/src/main/java/org/phenotips/data/permissions/internal/DefaultEntityPermissionsManager.java, components/entity-access-rules/api/src/main/java/org/phenotips/data/permissions/internal/DefaultEntityVisibilityManager.java, components/entity-access-rules/api/src/main/java/org/phenotips/data/permissions/internal/DefaultOwner.java, components/entity-access-rules/api/src/main/java/org/phenotips/data/permissions/internal/EntityAccessHelper.java, components/entity-access-rules/api/src/main/java/org/phenotips/data/permissions/internal/EntityAccessManager.java, components/entity-access-rules/api/src/main/java/org/phenotips/data/permissions/internal/EntityVisibilityManager.java, components/entity-access-rules/api/src/main/java/org/phenotips/data/permissions/internal/FilteringIterator.java, components/entity-access-rules/api/src/main/java/org/phenotips/data/permissions/internal/OwnerUpdateEventListener.java, components/entity-access-rules/api/src/main/java/org/phenotips/data/permissions/internal/SecureEntityAccess.java, components/entity-access-rules/api/src/main/java/org/phenotips/data/permissions/script/EntityPermissionsManagerScriptService.java, components/entity-access-rules/api/src/main/java/org/xwiki/security/authorization/ManageRight.java, components/entity-access-rules/api/src/test/java/org/phenotips/data/permissions/internal/DefaultEntityAccessManagerTest.java, components/entity-access-rules/api/src/test/java/org/phenotips/data/permissions/internal/DefaultEntityAccessTest.java, components/entity-access-rules/api/src/test/java/org/phenotips/data/permissions/internal/OwnerUpdateEventListenerTest.java, components/entity-access-rules/api/src/test/java/org/phenotips/data/permissions/script/EntityPermissionsManagerScriptServiceTest.java
- Added missing javadocs, null checks and annotations.
=> PT-3470: Fix checkstyle violations for the entity-access-rules-api module

components/family-studies/migrations/pom.xml, components/family-studies/migrations/src/main/java/org/phenotips/studies/family/migrations/R71507PhenoTips3423DataMigration.java, components/family-studies/migrations/src/main/resources/META-INF/components.txt, components/family-studies/migrations/src/test/java/org/phenotips/studies/family/migrations/R71507PhenoTips3423DataMigrationTest.java
@veronikaslc: this branch is based on top of PT-2617 branch - the only actual commits that need to be code-reviewed are the last two (clearly marked as PT-3423). However since it has to be tested together all the commits from PT-2617 branch are included in this pull request.
=> PT-3423: Implement a migrator from old internal pedigree format to new

components/patient-measurements/api/pom.xml, components/patient-measurements/api/src/main/java/org/phenotips/measurements/ComputedMeasurementHandler.java, components/patient-measurements/api/src/main/java/org/phenotips/measurements/MeasurementHandler.java, components/patient-measurements/api/src/main/java/org/phenotips/measurements/internal/AbstractMeasurementHandler.java, components/patient-measurements/api/src/main/java/org/phenotips/measurements/internal/BMIMeasurementHandler.java, components/patient-measurements/api/src/main/java/org/phenotips/measurements/internal/USLSMeasurementHandler.java, components/patient-measurements/api/src/test/java/org/phenotips/measurements/internal/ArmspanTest.java, components/patient-measurements/api/src/test/java/org/phenotips/measurements/internal/BMITest.java, components/patient-measurements/api/src/test/java/org/phenotips/measurements/internal/LowerSegTest.java, components/patient-measurements/api/src/test/java/org/phenotips/measurements/internal/USLSTest.java, components/patient-measurements/api/src/test/java/org/phenotips/measurements/internal/UpperSegTest.java, components/patient-measurements/resources/src/main/resources/resources/uicomponents/phenotips/measurements.js, components/patient-measurements/rest/pom.xml, components/patient-measurements/rest/src/main/java/org/phenotips/data/rest/ComputedMeasurementResource.java, components/patient-measurements/rest/src/main/java/org/phenotips/data/rest/internal/AbstractMeasurementRestResource.java, components/patient-measurements/rest/src/main/java/org/phenotips/data/rest/internal/DefaultComputedMeasurementResourceImpl.java
Authored with @marta- and @sdumitriu
=> [refactoring] PT-3296: Create interface for ComputedMeasurements

components/vocabularies/api/src/main/java/org/phenotips/vocabulary/internal/solr/DefaultSolrVocabularyResourceManager.java
=> PT-3534: After reindexing vocabularies, spellchecked suggestions no longer work

components/patient-data/impl/src/main/java/org/phenotips/data/internal/PatientExtendedPhenotypeUpdater.java
=> PT-2175: Extended negative prenatal phenotypes never stored

components/widgets/resources/src/main/resources/resources/uicomponents/widgets/extraGeneVariantData.css
Adjusted wrt cDNA input field width
=> PT-2936: Adjust the alignment of variants editing fields

components/patient-data/ui/src/main/resources/PhenoTips/PatientConsentConfiguration.xml
Disable entering specific patient information when mandatory status of consent is set to 'yes'
=> PT-2446: Consents administration: don't allow setting a consent as required for certain fields if it is already mandatory

components/family-studies/ui/src/main/resources/Families/WebHome.xml
Removed whitespace that was generating blank paragraph
=> [misc] Removed extra blank line on top of the Browse Families table

resources/utilities/upload_vcf.py
Python 3.6 script to upload the VCF file as an attachment for the given patient.
=> PT-3554: Create a script that would enable upload of vcf file to the given patient

components/skin/ui/src/main/resources/PhenoTips/Skin.xml
=> PT-3570: Decrease the frequency of auto save from 10 seconds to 1 minute

components/patient-access-rules/ui/src/main/resources/PhenoTips/AccessRightsManagement.xml
- Fixed unable to add collaborator
- Better duplicates detection in collaborators list
- Better owner accepted suggestion clearing using suggest widget
=> PT-3579: Unable to add collaborator

components/utilities/concurrency-locking/pom.xml, components/utilities/concurrency-locking/src/main/java/org/phenotips/locks/DocumentLockManager.java, components/utilities/concurrency-locking/src/main/java/org/phenotips/locks/internal/LockingListener.java, components/utilities/concurrency-locking/src/main/java/org/phenotips/locks/internal/TimeoutDocumentLockManager.java, components/utilities/concurrency-locking/src/main/resources/META-INF/components.txt, components/utilities/concurrency-locking/src/test/java/org/phenotips/locks/internal/LockingListenerTest.java, components/utilities/concurrency-locking/src/test/java/org/phenotips/locks/internal/TimeoutDocumentLockManagerTest.java, components/utilities/pom.xml, distribution/war/pom.xml
Temporary fix. Tests will be added soon.
=> PT-2238: Exception while saving a patient

components/patient-data/ui/src/main/resources/PhenoTips/PatientClass.xml, components/patient-data/ui/src/main/resources/PhenoTips/PatientTemplate.xml, resources/ui/src/main/resources/PhenoTips/EthnicitySearch.xml
- Switched back to the EthnicitySearch service
=> PT-3544: Free text entered as an ethnicity does not get suggested anymore

components/pedigree/resources/src/main/resources/pedigree/model/export.js
=> PT-3590: PED export omits cancers entered in the new cancer tab

components/widgets/resources/src/main/resources/resources/uicomponents/widgets/exportData.css, components/widgets/ui/src/main/resources/PhenoTips/Widgets.xml, components/widgets/ui/src/main/resources/XWiki/DateTimePicker.xml
- Added user icon in the beginning of the input field
=> PT-3580: Lookup fields in advanced filters and export/push dialog need to have a uniform look

components/skin/ui/src/main/resources/PhenoTips/Skin.xml
=> PT-3592: Homepage gadget extra action icons should be bigger

components/navigation/ui/src/main/resources/PhenoTips/DatabaseFilters.xml, components/patient-data/ui/src/main/resources/PhenoTips/PatientClass.xml, components/patient-data/ui/src/main/resources/PhenoTips/PatientSheetCode.xml, components/patient-data/ui/src/main/resources/PhenoTips/PatientSheetMacros.xml, components/widgets/resources/src/main/resources/resources/uicomponents/widgets/extraGeneVariantData.js
=> PT-3552: XSS vulnerability in patient form data

components/family-studies/rest/pom.xml, components/family-studies/rest/src/main/java/org/phenotips/studies/family/rest/internal/DefaultFamilyResourceImpl.java, components/family-studies/rest/src/test/java/org/phenotips/studies/family/rest/internal/DefaultFamilyResourceImplTest.java
=> PT-3597: Cannot delete a family via REST

components/users/ui/src/main/resources/PhenoTips/PhenoTipsGroupSheet.xml
=> PT-3577: Group cases are not displayed in Admin/Group/Cases

components/patient-data/rest/src/main/java/org/phenotips/data/rest/internal/DefaultPatientByLabeledExternalIdentifierResourceImpl.java, components/patient-data/rest/src/test/java/org/phenotips/data/rest/internal/DefaultPatientByLabeledExternalIdentifierResourceImplTest.java
- Refactored REST methods to return WebApplicationException for error responses for consistent handling
- Overall improved Exception handling
- Edit debug statements
- Fix tests and add some test cases for `create=false`
=> PT-3605: Fix tests and refactor method responses to throw exceptions

components/studies/ui/src/main/resources/PhenoTips/StudyBindingClass.xml
And:
PT-3610: View-only collaborators are presented with the option to change the study of a patient record
=> PT-3609: Users that are not subscribed to any studies cannot see when a patient record belongs to a study

distribution/hsqldb-database/pom.xml, pom.xml, resources/jetty/packaging/src/main/resources/start.sh
Fixed.
Building still doesn't work because of https://github.com/highsource/maven-jaxb2-plugin/issues/120
=> PT-3630: PhenoTips doesn't run on Java 9

components/base-war/src/main/webapp/resources/uicomponents/search/searchSuggest.js
=> PT-3625: Non-functional Go to search page displayed in the quick-search results

resources/jetty/packaging/src/main/resources/start.bat
=> PT-3648: PhenoTips won't run on Windows if username contains space character

components/widgets/ui/src/main/resources/PhenoTips/Widgets.xml
=> PT-3653: DetailsDialog date picker should be attached to the date input

components/base-war/src/main/webapp/resources/uicomponents/widgets/validation/scrollValidation.js
=> PT-3657: Edit mode is not detected correctly by scrollValidation

components/patient-data/impl/src/main/java/org/phenotips/data/internal/PhenoTipsPatient.java
=> PT-3558: Export as JSON is missing the Referrer (report creator) info

components/export/api/src/main/java/org/phenotips/export/internal/DataToCellConverter.java, components/export/ui/src/main/resources/PhenoTips/ExportPreferences.xml, components/patient-data-sharing/push-api/src/main/java/org/phenotips/data/push/internal/DefaultPushServerConfigurationResponse.java, components/patient-data-sharing/push-ui/src/main/resources/PhenoTips/PushPatient.xml, components/patient-data/impl/src/main/resources/ApplicationResources.properties, components/patient-data/ui/src/main/resources/PhenoTips/PatientConsentConfiguration.xml, components/patient-data/ui/src/main/resources/PhenoTips/UIX_Field__gene-variants.xml, components/patient-data/ui/src/main/resources/PhenoTips/UIX_Field__genes.xml, components/widgets/resources/src/main/resources/resources/uicomponents/widgets/exportData.js, components/widgets/resources/src/main/resources/resources/uicomponents/widgets/extraGeneVariantData.js, components/widgets/resources/src/main/resources/templates/geneVariantMacros.vm
Added new UIX genes extension that is generating UI only if gene-variants UIX is disabled
=> PT-3651: Add ability to consent/push/export genes and variants separately

components/vocabularies/ui/src/main/resources/PhenoTips/IndexVocabulary.xml
Enabling just reindex button instead of enabling the whole form
=> PT-3632: Upon successful reindexing corresponding vocabulary fields turn into edit mode

components/patient-data/ui/src/main/resources/PhenoTips/CheckID.xml
=> PT-3696: Include inaccessible records when checking the uniqueness of the external id

components/navigation/ui/src/main/resources/PhenoTips/LiveTableMacros.xml
=> PT-3698: Filtering for non-positive boolean values should also work when no value at all is set

components/base-war/pom.xml, components/base-war/src/main/java/com/xpn/xwiki/objects/classes/ComputedFieldClass.java, components/base-war/src/main/java/com/xpn/xwiki/objects/classes/PropertyClass.java
Fixed by backporting http://jira.xwiki.org/browse/XWIKI-13057
=> PT-3706: Measurements don't work for non-admin users

components/pedigree/resources/src/main/resources/pedigree/view/nodeMenu.js
=> PT-3600: Autocomplete/suggest inputs in the pedigree node popover retain input between different nodes

components/family-studies/ui/src/main/resources/PhenoTips/FamilyClass.xml, components/family-studies/ui/src/main/resources/PhenoTips/FamilyMacros.xml, components/family-studies/ui/src/main/resources/PhenoTips/FamilyReferenceClass.xml, components/family-studies/ui/src/main/resources/PhenoTips/FamilyTemplate.xml, components/family-studies/ui/src/main/resources/PhenoTips/FormMacros.xml, components/pedigree/resources/src/main/resources/pedigree/view/nodeMenu.js, components/pedigree/resources/src/main/resources/pedigree/view/patientDropLegend.js, components/pedigree/resources/src/main/resources/pedigree/view/personVisuals.js
=> PT-3581: Prevent opening same patient/family in multiple tabs from pedigree editor and patient form

components/base-war/src/main/webapp/templates/macros.vm
=> PT-3724: Remove two extra spaces in front of form title

components/users/ui/src/main/resources/PhenoTips/PhenoTipsGroupSheet.xml
=> PT-2091: User profile's setting label and icon are overlapped

components/consents/api/src/main/resources/ApplicationResources.properties
=> PT-3498: Modify "Update consents" button label to read "Update"

components/application-configuration/api/src/main/resources/ApplicationResources.properties, components/application-configuration/ui/src/main/resources/PhenoTips/DBConfigurationClass.xml, components/application-configuration/ui/src/main/resources/PhenoTips/LabeledIdentifierConfigurationClass.xml, components/application-configuration/ui/src/main/resources/PhenoTips/LabeledIdentifierGlobalSettings.xml, components/application-configuration/ui/src/main/resources/PhenoTips/LabeledIdentifierSettings.xml, components/base-war/src/main/webapp/templates/macros.vm, components/default-settings/src/main/resources/XWiki/XWikiPreferences.xml, components/family-studies/ui/src/main/resources/PhenoTips/FamilyReferenceClass.xml, components/navigation/ui/src/main/resources/data/WebHome.xml
=> PT-3720: Move SHOW EXTERNAL IDENTIFIERS... to the Admin's External ID configuration page

components/application-configuration/api/src/main/resources/ApplicationResources.properties, components/application-configuration/ui/src/main/resources/PhenoTips/LabeledIdentifierConfigurationClass.xml, components/application-configuration/ui/src/main/resources/PhenoTips/LabeledIdentifierGlobalSettings.xml, components/default-settings/src/main/resources/XWiki/XWikiPreferences.xml
=> PT-3742: Add uniqueness ID check configuration to Administration

components/patient-access-rules/ui/src/main/resources/PhenoTips/AccessRightsManagement.xml
=> PT-3748: Unable to transfer ownership to another user or group in a certain situation

components/patient-data/impl/src/main/resources/ApplicationResources.properties, components/patient-data/ui/src/main/resources/PhenoTips/PatientSheetCode.xml
Added custom function before fuzzy date validation
=> PT-3743: If DOB are marked as required only year of birth will be enforced

components/family-studies/ui/src/main/resources/PhenoTips/FamilyPedigreeInterface.xml, components/pedigree/resources/src/main/resources/pedigree/controller.js, components/pedigree/resources/src/main/resources/pedigree/editor.css, components/pedigree/resources/src/main/resources/pedigree/pedigree.js, components/pedigree/resources/src/main/resources/pedigree/view/studySelectionDialog.js, components/pedigree/ui/src/main/resources/PhenoTips/PedigreeInterface.xml, components/studies/ui/src/main/resources/PhenoTips/StudiesMacros.xml, components/studies/ui/src/main/resources/PhenoTips/StudyBindingClass.xml
=> PT-2134: When creating a new patient within pedigree editor, the system does not ask if the patient is a part of a study

components/family-studies/api/src/main/java/org/phenotips/studies/family/Pedigree.java, components/family-studies/api/src/main/java/org/phenotips/studies/family/internal/DefaultPedigree.java, components/family-studies/api/src/main/java/org/phenotips/studies/family/internal/PhenotipsFamilyRepository.java, components/pedigree/resources/src/main/resources/pedigree/model/import.js
note: PT-3719 "Write a migrator which updates pedigree JSONs to include all family members" may be added to this PR
=> PT-3709: Update add-to-family API to also modify pedigree JSON

components/pedigree/resources/src/main/resources/pedigree/editor.css, components/pedigree/resources/src/main/resources/pedigree/externalEndpoints.js, components/pedigree/resources/src/main/resources/pedigree/nodeMenuFields.js, components/pedigree/resources/src/main/resources/pedigree/view/nodeMenu.js, components/pedigree/ui/src/main/resources/PhenoTips/PedigreeInterface.xml
=> PT-3704: The id uniqueness is not checked when a patient record is populated from the pedigree editor

components/pedigree/resources/src/main/resources/pedigree/controller.js, components/pedigree/resources/src/main/resources/pedigree/editor.css, components/pedigree/resources/src/main/resources/pedigree/familyData.js, components/pedigree/resources/src/main/resources/pedigree/model/dynamicGraph.js, components/pedigree/resources/src/main/resources/pedigree/pedigree.js, components/pedigree/resources/src/main/resources/pedigree/view/nodeMenu.js
@sashaandjic please test. The problems are described in issue descriptions (PT-3761,  PT-3762).
One additional problem that was fixed is for PT-3704 where an "id is already taken" error message was not cleared when node menu was opened for other nodes
=> Pedigree 1.4rc1 bugfixes

components/patient-access-rules/ui/src/main/resources/PhenoTips/AccessRightsManagement.xml
=> PT-3763: Permissions changes cannot be saved by users who can't transfer ownership

components/users/ui/src/main/resources/PhenoTips/PhenoTipsGroupSheet.xml
=> PT-3690: Subgroup members should be able to see main group members and shared cases.

components/security/audit/frontend/src/main/resources/PhenoTips/AuditLogs.xml
=> PT-3747: Suggest widget in Audit does not respond to keyboard selection

components/pedigree/resources/src/main/resources/pedigree/controller.js, components/pedigree/resources/src/main/resources/pedigree/externalIdManager.js, components/pedigree/resources/src/main/resources/pedigree/patientDataLoader.js, components/pedigree/resources/src/main/resources/pedigree/pedigree.js, components/pedigree/resources/src/main/resources/pedigree/view/nodeMenu.js, components/pedigree/resources/src/main/resources/pedigree/view/person.js
@sashaandjic please check error messages, they should (probably) be reworded
=> PT-3759: The pedigree editor still allows duplicate external IDs

components/widgets/ui/src/main/resources/PhenoTips/ImageDisplayer.xml
Upon merging, this commit should be cherry-picked into stable-1.3.x
=> PT-3814: Attachment filenames are parsed for XWiki markup

components/family-studies/ui/src/main/resources/PhenoTips/FamilyFilters.xml
=> PT-3874: Allow disabling filters on the All Families table

components/navigation/ui/src/main/resources/PhenoTips/DatabaseFilters.xml
=> PT-3876: Improve data table performance by not using substring match for visibility filters

components/patient-contacts/src/main/java/org/phenotips/data/ContactInfo.java, components/patient-contacts/src/test/java/org/phenotips/data/ContactInfoTest.java
=> PT-3882: ContactInfo does not parse a string with multiple emails

components/widgets/resources/src/main/resources/resources/uicomponents/widgets/extraGeneVariantData.js
=> PT-3903: When a new variant is added in the Genes/Variants table, the variant table title does not display the gene name

components/patient-access-rules/ui/src/main/resources/PhenoTips/AccessRightsManagement.xml
=> PN-3908: Permissions dialog does not clean up cached data on dialog Cancel button clicked

components/entity-access-rules/rest/src/main/java/org/phenotips/data/permissions/rest/internal/NameAndEmailExtractor.java, components/patient-access-rules/ui/src/main/resources/PhenoTips/AccessRightsManagement.xml
Also fixed backend to consider that the group may be XWikiGroup and not only PhenoTipGroupClass
=> PT-3907: Default entity name to the id for permissions dialog

components/family-studies/api/src/main/java/org/phenotips/studies/family/Family.java, components/family-studies/api/src/main/java/org/phenotips/studies/family/internal/PhenotipsFamily.java, components/family-studies/api/src/main/java/org/phenotips/studies/family/internal/SecureFamily.java, components/family-studies/api/src/main/java/org/phenotips/studies/family/internal/export/PhenotipsFamilyExport.java, components/pedigree/resources/src/main/resources/pedigree/familyData.js, components/pedigree/resources/src/main/resources/pedigree/pedigreeEditorParameters.js, components/pedigree/resources/src/main/resources/pedigree/saveLoadEngine.js, components/pedigree/resources/src/main/resources/pedigree/view/okCancelDialogue.js, components/pedigree/ui/src/main/resources/PhenoTips/PedigreeMacros.xml
Need to be cherry-picked into stable when it is approved
=> PT-3853: Obfuscate pedigree tumbnail if "Warn about sensitive information" is checked

components/patient-data/indexing/src/main/java/org/phenotips/data/indexing/internal/SolrPatientIndexer.java
Note: when this is approved need to make a PR to stable-1.4.x as well. Stable-1.3.x does not need this.
=> PT-3938: Solr does not index patients until a full reindex is executed

components/patient-data/migrations/src/main/java/org/phenotips/data/internal/R74690PhenoTips3663DataMigration.java, components/patient-data/migrations/src/main/java/org/phenotips/data/internal/R74692PhenoTips3930DataMigration.java, components/patient-data/migrations/src/main/resources/META-INF/components.txt
=> PT-3930: Patient records entered in PhenoTips <1.4rc2 that has been upgraded to a version >= 1.4rc2 may have an empty PubMed ID

components/widgets/resources/src/main/resources/templates/geneVariantMacros.vm
Needs to be cherry-picked into `stable-1.3.x` and `stable-1.4.x`
=> PT-3953: Gene deletion on the patient form may delete incorrect genes

components/patient-data/impl/src/main/java/org/phenotips/data/internal/VariantCdnaCleanupEventListener.java, components/patient-data/impl/src/main/resources/META-INF/components.txt, components/patient-data/migrations/src/main/java/org/phenotips/data/internal/R1011091PhenoTips3947DataMigration.java, components/patient-data/migrations/src/main/java/org/phenotips/data/internal/R74694PhenoTips3947DataMigration.java, components/patient-data/migrations/src/main/resources/META-INF/components.txt, components/widgets/resources/src/main/resources/resources/uicomponents/widgets/geneVariantValidation.js
=> PT-3945-master: The variant's cDNA field may contain extra spaces and wrong prefixes

components/patient-data/impl/src/main/java/org/phenotips/data/internal/VariantCdnaCleanupEventListener.java, components/patient-data/impl/src/main/resources/META-INF/components.txt, components/patient-data/migrations/src/main/java/org/phenotips/data/internal/R74694PhenoTips3947DataMigration.java, components/patient-data/migrations/src/main/resources/META-INF/components.txt, components/widgets/resources/src/main/resources/resources/uicomponents/widgets/geneVariantValidation.js
=> PT-3945-stable-1.4.x: The variant's cDNA field may contain extra spaces and wrong prefixes

components/patient-access-rules/api/src/main/java/org/phenotips/data/permissions/internal/OwnerContactProvider.java, components/patient-access-rules/api/src/test/java/org/phenotips/data/permissions/internal/OwnerContactProviderTest.java
=> PT-3966: Fetch correct group name in owner contact provider

components/entity-access-rules/rest/src/main/java/org/phenotips/data/permissions/rest/internal/DefaultDomainObjectFactory.java, components/entity-access-rules/rest/src/main/resources/permissions.rest.model.xsd, components/patient-access-rules/ui/src/main/resources/PhenoTips/AccessRightsManagement.xml
Added url to the UserSummary object factory
=> PT-3942: Profile urls should be generated on the backend

components/patient-data/impl/src/main/java/org/phenotips/data/internal/SolvedData.java
=> PT-3946: When a patient is imported via JSON an empty PubmedID is not discarded

components/patient-data/impl/src/main/java/org/phenotips/data/internal/SolvedData.java
=> PT-3967: SolvedData throws NullPointerException on JSON import

components/patient-data/migrations/src/main/java/org/phenotips/data/internal/R71499PhenoTips2777DataMigration.java, pom.xml
To test: check that the build works.
=> [misc] Updated to checkstyle 8.18

components/patient-access-rules/ui/src/main/resources/PhenoTips/AccessRightsManagement.xml
Generate translation keys for this instance which can differ from the ones on default Phenotips.
=> PT-3975 Matchable visibility is undefined on detailed access rights table

components/entity-access-rules/rest/pom.xml, components/entity-access-rules/rest/src/main/java/org/phenotips/data/permissions/rest/internal/NameAndEmailExtractor.java
=> PT-3968: Modifying a group name is not reflected on patient/match table

components/base-war/pom.xml
=> [misc] Fixed dependency issue breaking build

components/patient-data/ui/src/main/resources/PhenoTips/UIX_Field__phenotype_suggestions.xml
=> PT-4009: PhenoType suggestions are no longer available

components/patient-data/ui/src/main/resources/PhenoTips/UIX_Field__phenotype_suggestions.xml
=> PT-4009 (stable): PhenoType suggestions are no longer available

distribution/war/pom.xml
This fixes the master build problem.
=> [misc] Upgraded pingback version again to work with XWiki 10+

components/vocabularies/api/src/main/java/org/phenotips/vocabulary/internal/solr/AbstractOBOSolrVocabulary.java, components/vocabularies/chebi/api/src/test/java/org/phenotips/vocabulary/internal/solr/ChEBIOntologyTest.java, components/vocabularies/hpo/api/src/test/java/org/phenotips/vocabulary/internal/solr/HumanPhenotypeOntologyTest.java
=> PT-4002: Reindexing HPO fails when an HPO term has more than one single value type field

components/patient-data/indexing/pom.xml, components/patient-data/indexing/src/main/java/org/phenotips/data/indexing/internal/R1011092PhenoTips4004DataMigration.java, components/patient-data/indexing/src/main/resources/META-INF/components.txt, components/patient-data/indexing/src/test/java/org/phenotips/data/indexing/internal/R1011092PhenoTips4004DataMigrationTest.java, components/patient-data/migrations/pom.xml, components/patient-data/migrations/src/main/resources/META-INF/components.txt
=> PT-4004: Patient Solr index should include ENS IDs and not gene names in the index

components/pedigree/resources/src/main/resources/pedigree/model/phenotipsJSON.js
Cherry-picked from 54c86cb403e3afa6f262371ce2aefe702a1fd422
=> PT-4018: Pedigree node life status not loaded from saved JSON (stable-1.4.x)

components/pedigree/resources/src/main/resources/pedigree/model/positionedGraph.js
=> PT-4027 Pedigree editor triggers cross-origin frame errors when launched in an iframe

components/pedigree/resources/src/main/resources/pedigree/model/import.js
=> PT-4028 Improve handling of non-standard GEDCOM files

components/pedigree/resources/src/main/resources/pedigree/view/printEngine.js, components/pedigree/ui/src/main/resources/PhenoTips/PedigreeMacros.xml
Fixed
Also, updated pedigree PDF export to match terminology and order of legend categories in the pedigree editor's print function
=> PT-3864 Pedigree printing omits legend
