phenotips/phenotips

components/diagnosis-suggestion/api/pom.xml, components/diagnosis-suggestion/api/src/main/java/org/phenotips/diagnosis/DiagnosisService.java, components/diagnosis-suggestion/api/src/main/java/org/phenotips/diagnosis/internal/DefaultDiagnosisService.java, components/diagnosis-suggestion/api/src/main/java/org/phenotips/diagnosis/script/DiagnosisScriptService.java, components/diagnosis-suggestion/api/src/test/java/org/phenotips/diagnosis/internal/DefaultDiagnosisServiceTest.java, components/diagnosis-suggestion/ui/src/main/resources/PhenoTips/DiseasePredictService.xml, pom.xml
Fixed by not searching ontology for free-input terms
=> Issue #1527: Non-standard phenotypes break the OMIM suggestions

components/patient-data/ui/src/main/resources/PhenoTips/PatientSheetCode.xml
Prevent page navigation when clicking section show/hide buttons.
Oops - I missed these buttons during the last set of changes on this branch.
=> Issue #1492: Expand/collapse all should be made more visual

components/patient-data/ui/src/main/resources/PhenoTips/PatientSheet.xml, components/widgets/ui/src/main/resources/PhenoTips/TabelarDataMacros.xml
This PR includes a fix for the bug in PR #1578, where the new reject row would not be filled with the data from the original row. The issue was that ```observe()``` was being invoked on ```undefined``` (returned by ```newRow.down('a.reject')```) and then the function was being aborted, causing the ```extradata:added``` event to not be fired.
=> Issue #1573: Newly added candidate genes don't get the "reject" button

components/specificity-meter/ui/src/main/resources/PhenoTips/SpecificityMetricWidget.xml
Change in the specificity metric value fires the
phenotype:specificity-meter:change event which data { "value":
[value], "title": [title] }
=> Issue #1613: Publish XWiki JavaScript event when the value of the specificity widget score on the patient form changes

components/solr-access-service/api/pom.xml, components/solr-access-service/api/src/main/java/org/phenotips/solr/HPOScriptService.java, components/solr-access-service/api/src/test/java/org/phenotips/solr/HPOScriptServiceTest.java, components/solr-access-service/api/src/test/java/org/phenotips/solr/SuggestedPhenotypeTest.java, components/solr-access-service/api/src/test/resources/hpo-test.obo
Commit history on this branch is a bit messed up. I accidentally wrote the measurement tests on the master branch, then branched to write these solr test and the change. 
The change to HPOScriptService.java here is due a problem found in testing. When crt.get("is_a") finds only one ancestor, it returns a String not a List<String>
=> Solr access tests

components/pedigree/resources/src/main/resources/pedigree/model/export.js
When exporting in a BOADICEA format, treats 'other' sex the same as 'unknown' sex
=> issue#1654 Add 'Other' as an option for the patient's sex

components/pedigree/resources/src/main/resources/pedigree/controller.js
Fixed by cloning if updated element is of a type 'object'.
=> Issue #1842: Undo does not work for some changes in pedigree editor. 

components/patient-data/impl/src/main/java/org/phenotips/data/internal/controller/AbstractComplexController.java
Changed `AbstractComplexController` to avoid the following compiler warnings:
```
[WARNING] /phenotips/components/patient-data/impl/src/main/java/org/phenotips/data/internal/controller/AbstractComplexController.java:[78,17] found raw type: com.xpn.xwiki.objects.BaseProperty
missing type arguments for generic class com.xpn.xwiki.objects.BaseProperty<R>
[WARNING]/phenotips/components/patient-data/impl/src/main/java/org/phenotips/data/internal/controller/AbstractComplexController.java:[91,50] unchecked cast
required: T
found:    java.lang.Object
[WARNING] /phenotips/components/patient-data/impl/src/main/java/org/phenotips/data/internal/controller/AbstractComplexController.java:[164,50] unchecked cast
required: java.util.List<T>
found:    java.lang.Object
```
=> Suppress cast warnings in AbstractComplexController

components/patient-data/impl/src/main/java/org/phenotips/data/internal/controller/GeneListController.java, components/patient-data/impl/src/main/java/org/phenotips/data/internal/controller/RejectedGeneListController.java, components/patient-data/impl/src/main/java/org/phenotips/data/internal/controller/VersionsController.java, components/patient-data/impl/src/test/java/org/phenotips/data/internal/controller/GeneListControllerTest.java, components/patient-data/impl/src/test/java/org/phenotips/data/internal/controller/VersionsControllerTest.java
- Added test suite for GeneListController (based on @veronikaslc's VariantListControllerTest in PR) (PT-2144)
- Added test for VersionController (PT-2144)
- Added null test on response of `getXObjects` in VersionController and GeneListController (PT-2143)
=> Fix for ListController export with deleted objects

components/patient-data/indexing/src/main/java/org/phenotips/data/indexing/internal/SolrPatientIndexer.java, resources/solr-configuration/src/main/resources/patients/conf/schema.xml
The actual phenotypes are copied into Solr fields according to their type:
- present features -> `phenotype`
- absent features -> `negative_phenotype`
- present prenatal features -> `prenatal_phenotype`
- absent prenatal features -> `negative_prenatal_phenotype`
The ancestor hierarchy is merged across all types and stored in two fields:
- `extended_phenotype` - all present phenotypes, regardless of type
- `extended_negative_phenotype` - all absent phenotypes, regardless of type
This PR replaces #1886 and #1909.
=> PT-825: include phenotype ancestors in patient index

components/skin/ui/src/main/resources/PhenoTips/UIXSheet.xml, components/vocabularies/hpo/ui/src/main/resources/PhenoTips/FormDesigner.xml
This pull request fixes two related bugs:
- When creating a new user interface extension, the title of the extension is cut off and displayed as garbage after the "Title" field.
- If no title parameter is specified, the patient form designer falls back to displaying the extension title, but incorrectly converts the double underscores to an underline.
See the screenshots below.
=> Escape UIX page titles when needed

components/patient-data/indexing/pom.xml, components/patient-data/indexing/src/main/java/org/phenotips/data/indexing/internal/SolrPatientIndexer.java, components/patient-data/indexing/src/test/java/org/phenotips/data/indexing/internal/SolrPatientIndexerTest.java, resources/solr-configuration/src/main/resources/patients/conf/schema.xml
- Based on @veronikaslc's commit 480d1a90
- Refactored gene indexing to use constants and avoid switch statement
- Index genes with blank status as candidates
- Should work even before merging in unified gene section (#1913)
Replaces #1897.
=> PT-2188: Added genes to patient index

components/application-configuration/api/src/main/java/org/phenotips/configuration/internal/global/DefaultRecordSection.java, components/base-war/src/main/java/com/xpn/xwiki/plugin/skinx/CssSkinFileExtensionPlugin.java, components/base-war/src/main/java/com/xpn/xwiki/plugin/skinx/JsSkinExtensionPlugin.java, components/base-war/src/main/java/com/xpn/xwiki/plugin/skinx/JsSkinFileExtensionPlugin.java, components/export/api/src/main/java/org/phenotips/export/internal/ConversionHelpers.java, components/ncbieutils-services/api/src/main/java/org/phenotips/ncbieutils/internal/AbstractSpecializedNCBIEUtilsAccessService.java, components/patient-tools/src/main/java/org/phenotips/tools/PropertyDisplayer.java, components/solr-access-service/api/src/main/java/org/phenotips/solr/AbstractSolrScriptService.java, components/users/api/src/main/java/org/phenotips/groups/internal/DefaultGroupManager.java, components/vocabularies/api/src/main/java/org/phenotips/vocabulary/internal/solr/AbstractSolrVocabulary.java, components/vocabularies/omim/api/src/main/java/org/phenotips/vocabulary/internal/solr/OmimSourceParser.java
This patch set makes PhenoTips use best practices when dealing with strings, as identified by `pmd -d . -R java-strings`:
http://pmd.sourceforge.net/pmd-5.2.0/pmd-java/rules/java/strings.html#InefficientStringBuffering
http://pmd.sourceforge.net/pmd-5.2.0/pmd-java/rules/java/strings.html#InsufficientStringBufferDeclaration
http://pmd.sourceforge.net/pmd-5.2.0/pmd-java/rules/java/strings.html#UseIndexOfChar
http://pmd.sourceforge.net/pmd-5.2.0/pmd-java/rules/java/strings.html#AppendCharacterWithChar
=> Speed up string operations

components/patient-tools/src/main/java/org/phenotips/tools/FormGroup.java
This minimizes reallocation, a costly operation.
=> Guess how much space the StringBuilder in FormGroup.display will require

components/patient-data/impl/src/main/java/org/phenotips/data/internal/controller/AbstractComplexController.java, components/patient-data/impl/src/main/java/org/phenotips/data/internal/controller/PrenatalPhenotypeController.java
Not sure if this is correct, but it seems as though the only possible case where `isCodeFieldsOnly()` will be overridden to return True is when the value of `< T >` in `AbstractComplexController<T>` is equal to `List<VocabularyProperty>` @sdumitriu Is it possible that a class could extend `AbstractComplexController<List<VocabularyProperty>>` and require that `isCodeFieldsOnly()` return False?
=> Changed isCodeFieldsOnly() to check type parameter of AbstractComplexController

components/pedigree/resources/src/main/resources/pedigree/model/import.js
Somehow BaseGraph used to be imported into the current scope. My guess is that when the build order changed, BaseGraph could no longer be accessed from import.js without qualification. All but three references to BaseGraph.TYPE in import.js were already qualified, so this change also improves the file's internal consistency.
=> PT-2304: Import functionality is broken in pedigree editor

components/vocabularies/hpo/ui/src/main/resources/PhenoTips/FormDesigner.xml
Currently, the patient form editor displays headings in all caps, whereas the patient form itself does not. This makes it hard to see from the form editor how the form will actually be displayed.
I've put together a simple fix for this problem that displays the headings in bold and color instead of all caps:
**- Before -**
**- After -**
=> Use bold and color, not all caps, for headers in the patient form editor

components/patient-data/ui/src/main/resources/PhenoTips/PatientSheetCode.xml, components/studies/ui/src/main/resources/PhenoTips/StudyBindingClass.xml
Currently, the mouse cursor set on the change-study button makes it look like it is not clickable, and the cursor set on patient data headings makes it look like they are clickable. These two commits change the cursors back to the defaults that web users expect.
=> Use default cursors for headers and the change-study button

components/studies/ui/src/main/resources/PhenoTips/StudyBindingClass.xml, components/vocabularies/hpo/ui/src/main/resources/PhenoTips/FormDesigner.xml, components/widgets/ui/src/main/resources/PhenoTips/ImageDisplayer.xml
There are numerous XHTML syntax errors in PhenoTips that prevent scraping pages as XML. The multiplicity of syntax errors also makes it hard to find other, more serious problems.
=> Fix XHTML syntax errors

components/base-war/pom.xml, distribution/war/pom.xml
This depends on https://github.com/phenotips/pingback and a running instance of ElasticSearch, the configuration for which is provided in pingback repo.
=> Ping back number of users and cases from all installed PT instances

components/widgets/ui/src/main/resources/PhenoTips/ImageDisplayer.xml
This partially reverts commit 1e8b1a741ebbd60cf829bbc830dd90548ac17afd.
Fixes https://github.com/phenotips/phenotips/commit/1e8b1a741ebbd60cf829bbc830dd90548ac17afd#commitcomment-16837262
My apologies for not noticing that $qString was already passed to escapetool.xml and $actionURL was not.
=> Single-escape $qString and double-escape $actionURL in ImageDisplayer

components/application-configuration/ui/src/main/resources/PhenoTips/DBConfigurationClass.xml, resources/ui/src/main/resources/XWiki/ConfigurableClassMacros.xml
ConfigurableClassMacros.xml expects attributes to be single-quoted just
like the ones that XWiki generates are. If double quotes are used
instead, it will change the for attributes on the labels without
changing the id attributes on the inputs to match.
If the input is inside a label tag, or there is no input tag at all, the
for attribute is not necessary.
=> Fix for and id attributes to link labels to inputs

components/navigation/ui/src/main/resources/data/WebHome.xml, components/patient-data-sharing/push-ui/src/main/resources/PhenoTips/PushPatientConfiguration.xml, components/patient-data-sharing/receiver-ui/src/main/resources/data/ReceivePatientConfiguration.xml, components/patient-data/ui/src/main/resources/PhenoTips/PatientConsentConfiguration.xml, components/user-profile-ui/src/main/resources/XWiki/AdminUserProfileSheet.xml, resources/ui/src/main/resources/PhenoTips/UIX Directory.xml
This fixes the syntax of the "Patient data consents configuration", "Phenotypes displayed by default", "Receive Patient configuration", "UIX", and "User Profile" pages.
=> Escape ampersands on administration pages

components/pedigree/resources/src/main/resources/pedigree/view/exportSelector.js
=> PT-2435: Use underscores rather than spaces in pedigree export filenames.

components/patient-measurements/ui/src/main/resources/PhenoTips/MeasurementsClass.xml
From JIRA: "The quick fix is to display nothing if we get -1 on evaluation. The better fix is to get the data for 0-2y."
=> PT-924: The "quick fix" for displaying hand length percentile when taken < 2 years old.

components/patient-data/impl/src/main/java/org/phenotips/data/internal/PhenoTipsPatientConsentManager.java
Fixed. Note that in JIRA, PT-2566 refers to line breaks. That was fixed client-side in PT-2583; this fixes the server-side code such that HTML tags work as expected (including line breaks, paragraphs, etc.)
=> PT-2566: HTML tags (specifically p and div) in consent label and description

components/specificity-meter/ui/src/main/resources/PhenoTips/SpecificityMetricWidget.xml
Currently, on initialization of the specificity meter (on page load), an event is always fired with value "0", even though this is not the actual specificity score. That event should not be fired because it does not represent an actual change in value, nor does it contain the actual specificity score.
This change is necessary for a downstream module that triggers certain behaviour when the specificity score changes. With the current "false positive" behaviour of the specificity meter, the downstream module does not work properly.
=> Modify the specificity meter to not fire an event on initialization

components/pedigree/resources/src/main/resources/pedigree/view/exportSelector.js
Bugfix: if response has no JSON and no link to show was silently ignored
=> PT-2230: Allow exporting pedigree as an image from within pedigree editor.

components/family-studies/api/src/main/java/org/phenotips/studies/family/internal/PhenotipsFamilyRepository.java, components/pedigree/ui/src/main/resources/PhenoTips/PedigreeMacros.xml, components/skin/ui/src/main/resources/PhenoTips/ContentTopMenu.xml
Fixed 3 problems:
- `deleteFamily` workflow was wrong when the deletion of all members was requested
- Family Id got "lost" before actually sending the request to delete the family
- CSRF token was not sent from client side for the `deletefamily` action
=> PT-2871: Delete patient and family functionality is broken

components/pedigree/resources/src/main/resources/pedigree/editor.css
Reverting commits done for PT-2866: Pedigree legend does not scale if there are many annotations (eg ~30 phenotypes), which are causing the problem (PR #2154).
=> PT-2961: Legend is broken in pedigree editor

components/export/ui/src/main/resources/PhenoTips/ExportPreferences.xml
In [this commit for PT-2932](https://github.com/phenotips/phenotips/commit/b791fcb56dced61ad895b1bb9a7b8396acb17726), the generation of the selection tools was moved from JavaScript to Velocity, but now the selection tools are generated ONLY in the push dialog, not the Export Excel/JSON dialog. However, [the JavaScript still tried to attach behaviors to the (non-existing) tools](https://github.com/phenotips/phenotips/commit/b791fcb56dced61ad895b1bb9a7b8396acb17726#diff-beef42dea801bc57f407ac4f98c830d4R317) which produced an error and prevented the rest of the code from running.
=> Fixing regressions introduced by PT-2932 (PT-3021, PT-3022, PT-3031)

components/widgets/ui/src/main/resources/PhenoTips/Widgets.xml
This rule caused the link to HPO to be misplaced in tooltips inside the Ontology browser. It's 5y old and doesn't seem to have any other effects anymore.
Before:
After:
=> [misc] Tooltip layout fix

components/patient-data/ui/src/main/resources/PhenoTips/UIX_Field__phenotype.xml
=> PT-3166: HPO Ids should not be visible in phenotype suggestions

components/export/api/src/main/java/org/phenotips/export/internal/DataToCellConverter.java, components/export/api/src/main/java/org/phenotips/export/internal/SheetAssembler.java, components/export/api/src/main/resources/ApplicationResources.properties
Diagnosis comments/notes will still only export if the Final Diagnosis field is selected to be exported. I did not create an option to export them separately because the export menu will be redone soon, but I did place them in the render list for the export menu so that they are given their own export option in the future.
=> PT-3187: Rename Disorders column in excel export, create separate header for comments

components/pedigree/ui/src/main/resources/PhenoTips/PedigreeMacros.xml
Done. Accidentally introduced when translating the pedigree thumbnail menu in commit 6379c7e93e4fb22 for https://phenotips.atlassian.net/browse/PT-2849 .
=> PT-3309: Remove quotation marks from Export png/svg buttons

components/navigation/ui/src/main/resources/PhenoTips/LiveTableMacros.xml
To test without the permissions module: edit `resources/ui/pom.xml` and remove the dependency on `patient-access-rules-ui`, then rebuild.
=> PT-3313: Not all patients are shown in the "All Patients" table when the permissions module is not installed

components/navigation/ui/src/main/resources/PhenoTips/LiveTableMacros.xml
Fixed regression: filtering by referrer or last author in the export dialog doesn't work anymore.
=> PT-3278: Export doesn't take into account the filters for genes and for clinical diagnosis

components/patient-access-rules/ui/src/main/resources/PhenoTips/PatientAccessRightsManagement.xml
Done by:
* firing some custom events when initializing/updating the permissions dialog
* turning some blocks of code into named functions that can be reused by extensions
From the PhenoTips user's perspective, this refactoring should have no effect on the functionality of the permissions dialog.
**This is on top of @veronikaslc 's refactoring of the permissions dialog to use Permissions REST (PT-3210, #2322).**
See also PR #2379 (same thing, on top of the master branch).
=> PT-3324: Refactor the Permissions manager dialog to enable extending it with custom sharing options

components/pedigree/resources/src/main/resources/pedigree/view/personHoverbox.js
=> PT-3357: In pedigree editor do not show A&W options on hoverboxes for patients which are read-only for current user

components/patient-data/rest/pom.xml, components/patient-data/rest/src/main/java/org/phenotips/data/rest/PatientByExternalIdResource.java, components/patient-data/rest/src/main/java/org/phenotips/data/rest/PatientResource.java, components/patient-data/rest/src/main/java/org/phenotips/data/rest/internal/DefaultPatientByExternalIdResourceImpl.java, components/patient-data/rest/src/main/java/org/phenotips/data/rest/internal/DefaultPatientResourceImpl.java, components/patient-data/rest/src/test/java/org/phenotips/data/rest/internal/DefaultPatientByExternalIdResourceImplTest.java, components/patient-data/rest/src/test/java/org/phenotips/data/rest/internal/DefaultPatientResourceImplTest.java
Depends on #2348. First five commits are from that pull request.
For testing:
* Update patient by ID:
- update
```curl -X POST -u <username>:<password> -d '<json>' http://localhost:<port>/rest/patients/<id>?method=PUT -H "Content-Type:application/json"```
- merge
``` curl -X POST -u <username>:<password> -d '<json>' http://localhost:<port>/rest/patients/<id>?method=PATCH -H "Content-Type:application/json"```
* Update patient by external ID:
- update
```curl -X POST -u <username>:<password> -d '<json>' http://localhost:<port>/rest/patients/eid/<e_id>?method=PUT -H "Content-Type:application/json"```
- merge
``` curl -X POST -u <username>:<password> -d '<json>' http://localhost:<port>/rest/patients/eid/<e_id>?method=PATCH -H "Content-Type:application/json"```
=> PT-3034: Allow method PATCH on patient resources

components/navigation/ui/src/main/resources/data/WebHome.xml
Changed the default columns. Unfortunately, until we implement support for column reordering in administration, the owner column may end up in a different position when an Admin modifies the livetable columns in a running PhenoTips.
=> PT-3376: Live tables: replace "Reported by" column with "Owner"

components/pedigree/resources/src/main/resources/pedigree/editor.css
Quick fix: don't show the browse button. It was already hidden for phenotype suggestions.
=> PT-3428: BROWSE RELATED TERMS button does not work in pedigree editor

components/pedigree/resources/src/main/resources/pedigree/pedigreeDate.js
For steps to reproduce, see [PT-3446](https://phenotips.atlassian.net/browse/PT-3446) and [PT-3449](https://phenotips.atlassian.net/browse/PT-3449).
=> PT-3446 and PT-3449: Pedigree functionality breaks when attempting to display dates with decade (not year) plus day and month

components/pedigree/resources/src/main/resources/pedigree/controller.js, components/pedigree/resources/src/main/resources/pedigree/editor.css, components/pedigree/resources/src/main/resources/pedigree/externalEndpoints.js, components/pedigree/resources/src/main/resources/pedigree/model/dynamicGraph.js, components/pedigree/resources/src/main/resources/pedigree/patientDataLoader.js, components/pedigree/resources/src/main/resources/pedigree/saveLoadEngine.js, components/pedigree/resources/src/main/resources/pedigree/undoRedoManager.js, components/pedigree/resources/src/main/resources/pedigree/view/legend.js, components/pedigree/resources/src/main/resources/pedigree/view/nodeMenu.js, components/pedigree/resources/src/main/resources/pedigree/view/okCancelDialogue.js, components/pedigree/resources/src/main/resources/pedigree/view/patientDropLegend.js, components/pedigree/resources/src/main/resources/pedigree/view/saveLoadIndicator.js
When a patient is unlinked, there is now a new button in the corner of the dialogue to remove the patient record being unlinked.
In addition to the obvious functionality (record deletion/error handling) need to make sure undo/redo works as expected, which in this case means "previous pedigree states look as they used to, except that the deleted record is removed". This should be so for all "undo" states, including those produced by changes unrelated to this patient record.
=> PT-3285: In pedigree, offer an option to delete unlinked patient records

components/family-studies/migrations/pom.xml, components/family-studies/migrations/src/main/java/org/phenotips/studies/family/migrations/R71507PhenoTips3423DataMigration.java, components/family-studies/migrations/src/main/java/org/phenotips/studies/family/migrations/R71508PhenoTips3424DataMigration.java, components/family-studies/migrations/src/main/resources/META-INF/components.txt, components/family-studies/migrations/src/test/java/org/phenotips/studies/family/migrations/R71507PhenoTips3423DataMigrationTest.java, components/family-studies/migrations/src/test/java/org/phenotips/studies/family/migrations/R71508PhenoTips3424DataMigrationTest.java, components/pedigree/resources/src/main/resources/pedigree/model/import.js
For testing, first need to migrate "old family studies" data, then used migrated pedigrees (which will be in "simple JSON" format, as opposed to "old internal") as input for this migrator
For reviewers: only the last two commits are for this issue, all others are from branches this is based on
=> PT-3424: Implement a migrator from auto-generated internal pedigree format

components/export/api/pom.xml, components/export/api/src/main/java/org/phenotips/export/internal/ConversionHelpers.java, components/export/api/src/main/java/org/phenotips/export/internal/DataToCellConverter.java, components/export/api/src/test/java/org/phenotips/export/internal/ConversionHelpersTest.java
A fix for sorting phenotype list by predefined categories obtained from configuration. Currently not used in codebase.
=> [misc] Fixing sorting phenotypes by categories in helper class

components/specificity-meter/ui/src/main/resources/PhenoTips/SpecificityMetricWidget.xml
This is a follow-up to https://github.com/phenotips/phenotips/pull/2085. The issue is now that the update event is not fired initially in the case that the score is 0.
This change fixes that issue, making the update event always fire when the score is actually calculated for the first time, even if the score is 0.
=> Modify the specificity meter to always fire an event on first update

components/skin/ui/src/main/resources/ColorThemes/Kiwi.xml, components/skin/ui/src/main/resources/ColorThemes/Orange.xml
This affects the Kiwi and Orange color themes.
=> PT-3517: Use lighter shade of gray for placeholder text displayed in the genetic variants fields

components/widgets/ui/src/main/resources/PhenoTips/YesNoNAPicker.xml
Excluding YesNoNA pickers with values "0" and "1" from HPO terms syncing
=> PT-2391: Clicking N/A on a dropdown prenatal phenotype doesn't do the same on the duplicate.

components/navigation/ui/src/main/resources/PhenoTips/DBWebHomeSheet.xml
Fixed regression: on the "Browse all patients/families" pages, the advanced filters collapse/expand doesn't work nice:
- in Firefox, the guillemet appears below the blue title bar instead of inside it
- in Chrome, the title bar collapses to the right instead of the left
=> PT-3488: Pedigree action buttons not looking good when scaling down below 90%

components/patient-data/impl/src/main/java/org/phenotips/data/internal/controller/VariantListController.java
Sending an empty array for the variants key in a REST PUT request should empty the list of variants.
=> PT-3565: Variants cannot be deleted via the REST patient API

components/patient-data/ui/src/main/resources/PhenoTips/PatientSheetMacros.xml
Adding `ajax=1` to the request causes XWiki to return an HTTP 204
instead of redirecting to the full patient form
=> Improve performance of "clear details" for phenotype metadata

pom.xml
Not only that it doesn't crash, but it is actually a lot faster.
=> PT-3571: Resolve text mining issues and turn it on by default

components/patient-data/impl/src/main/java/org/phenotips/data/internal/controller/FeaturesController.java
There is a problem in the patient data controller code: the code modifies its input data while it was only supposed to read and use it. Unlike 1.3.x this does not manifest itself in any visible way, but it may still become a problem later one if usage patters will change. To test just need to make sure patient "update from JSON"  works as expected for features and non-standard features (users of this feature include push and REST)
=> PT-3586: Input JSON is modified by FeaturesController

components/pedigree/resources/src/main/resources/pedigree/saveLoadEngine.js, components/pedigree/resources/src/main/resources/pedigree/view.js
Added correct pedigree support for family members that were added to a family outside of pedigree editor
(and thus are not in pedigree even in "unlinked" form, e.g. via a data pull from CLIN)
=> PT-3379: Families should support members that are not assigned to an individual in the pedigree

components/pedigree/resources/src/main/resources/pedigree/model/dynamicGraph.js
@sashaandjic talk with me about testing
=> PT-3708: Automatic layout may leave pedigree in an un-saveable un-exportable state

components/patient-data/impl/src/main/java/org/phenotips/data/internal/EmptyGenotypeObjectsRemover.java
Fixed NPE if there are no genes and variants
=> PT-3674: When removing genes from a person in pedigree editor, all associated gene variants need to be removed too

components/patient-data/impl/src/main/java/org/phenotips/data/internal/controller/AdditionalDocumentsController.java, components/patient-data/impl/src/main/java/org/phenotips/data/internal/controller/AdditionalImagesController.java, components/patient-data/impl/src/main/java/org/phenotips/data/internal/controller/Attachment.java, components/patient-data/impl/src/main/java/org/phenotips/data/internal/controller/AttachmentAdapterFactory.java, components/patient-data/impl/src/main/java/org/phenotips/data/internal/controller/MedicalReportsController.java, components/patient-data/impl/src/test/java/org/phenotips/data/internal/controller/AdditionalDocumentsControllerTest.java, components/patient-data/impl/src/test/java/org/phenotips/data/internal/controller/AdditionalImagesControllerTest.java, components/patient-data/impl/src/test/java/org/phenotips/data/internal/controller/AttachmentAdapterFactoryTest.java, components/patient-data/impl/src/test/java/org/phenotips/data/internal/controller/MedicalReportsControllerTest.java
Fixed by defaulting to including only a link to an attachment in Patient.toJSON() (for medical reports, images and "additional documents")
=> PT-3812: Saving pedigrees fails when family members have medical reports attached

pom.xml
maven-javadoc-plugin version 3.0.1 fails build with "Failure to find org.phenotips:phenotips-taglets:jar:1.8"
=> [misc] Revert javadoc plugin update

components/family-studies/ui/src/main/resources/PhenoTips/FamilyFilters.xml
Forgot to add the $exclusions parameter to the macro definition
=> PT-3874: Allow disabling filters on the All Families table

components/pedigree/resources/src/main/resources/pedigree/view/nodeMenu.js
Bug fix.
`editor.getGeneLegend(legendType)` will return `null` if there is no associated legend with the gene. Examples would be statuses of "Tested Negative" and "Rejected Candidate". We need to check for a null value before calling `.getGeneColor()`
I tested this small fix on my browser directly using dev tools. Please test on VM (once deployment completes): http://172.20.4.111:8080/
=> PT-3959: "Tested Negative/Rejected Candidate" Gene breaks Pedigree Editor

components/entity-access-rules/rest/src/main/java/org/phenotips/data/permissions/rest/internal/NameAndEmailExtractor.java
Fetch correct group name in OwnerRepresentation
=> PT-3968: Modifying a group name is not reflected on patient/match table

components/pedigree/resources/src/main/resources/pedigree/model/export.js
Quick fix. `isSet()` returns `true` if any date field was set. `isComplete()` returns `true` if the year is set (a bit misleading).
Since date to timestamp conversion requires at least the year field, using `isComplete()` is the proper check.
Many functions including `toJSDate()` check for the year being present, otherwise it returns null.
The `birthDate` also should use `isComplete()`, otherwise `NaN` will be on the export instead of `0` when there is a node without a birth year.
~There are other uses of `isSet()` that I'll take a look at.~
This fixes the bug and keeps fuzzy date behaviour the same. Uses of `isSet()` elsewhere seem to be valid. Tested locally, but should do more edge case testing.
To test:
- Spin up a VM and follow instructions on original ticket to double check bug is …
=> PT-3971 BOADICEA export breaks if an individual has a date of death specified without a year

components/vocabularies/hgnc/api/src/main/java/org/phenotips/vocabulary/internal/solr/GeneNomenclature.java
Also need to cherry-pick into stable-1.4.x
=> PT-3970: If a gene name contains a colon Solr queries searching for the gene fail

components/pedigree/resources/src/main/resources/pedigree/view/personPlaceholderVisuals.js
This bug happens when deleting a lone child. 
The deletion logic for an only child creates an invisible placeholder node (as the algorithms require a child). The blocking element was a highlight box that is created for any type of node. This highlight box is used to indicate which nodes contain a certain gene or phenotype upon hover-over.  Since it should never appear or be used on an invisible placeholder node, it should be permissible to remove it during creation.
Tested briefly using dev tools. Need to test more thoroughly on an instance.
A more time consuming option would be to refactor the onlyChild deletion logic (depreciate the need for `placeholderNode`) and re-test the algorithm behaviour. Another option would be to only generate the highlight box when actually needed, which …
=> PT-3890 Deleted nodes are not fully removed and block drag actions

components/base-war/src/main/webapp/templates/macros.vm
This change is needed in order to allow livetables to point to a rest endpoint instead of the a document.
It only gets triggered if the `resultPage` starts with a `/`.
```
#set ($options = {
'className'         : $patientClassName,
'translationPrefix' : 'patient.livetable.',
'rowCount'          : 50,
'maxPages'          : 10,
'selectedColumn'    : $config.getProperty('livetableSortColumn').value,
'defaultOrder'      : 'asc',
'topFilters'        : "${topFilters}${columnFiltersContent}",
'resultPage'        : '/rest/...'
})
```
=> Add the ability to set the livetable backend to a custom url

components/gene-panels/ui/src/main/resources/PhenoTips/PanelsDisplay.xml
Fixed the CSS selector that was too broad and affected more elements than originally intended.
=> PT-3981: After visiting a "secondary action" link, the text becomes white and therefore unreadable in the default color theme

components/base-war/src/main/webapp/resources/uicomponents/widgets/userpicker/userPicker.js, components/patient-access-rules/ui/src/main/resources/PhenoTips/AccessRightsManagement.xml, components/users/ui/src/main/resources/XWiki/XWikiGroupSheet.xml
- JS did not escape HTML for names. Use PrototypeJS's `.escapeHTML()`
- Use `getDisplayTitle()` which is already escaped, instead of `plainTitle` for group names
These are front end changes and need to be tested more thoroughly.
=> PT-3979 JS injection via group names

components/patient-access-rules/ui/src/main/resources/PhenoTips/AccessRightsManagement.xml
=> PT-4006: Tooltips width is too narrow for genes dropdown

components/patient-data/migrations/src/main/java/org/phenotips/data/internal/R52091PhenoTips670DataMigration.java, components/patient-data/migrations/src/main/java/org/phenotips/data/internal/R54693PhenoTips1500DataMigration.java, components/patient-data/migrations/src/main/java/org/phenotips/data/internal/R74690PhenoTips3663DataMigration.java, components/patient-data/migrations/src/main/java/org/phenotips/data/internal/R74692PhenoTips3930DataMigration.java, components/patient-measurements/migrations/src/main/java/org/phenotips/measurements/internal/R45190PhenoTips362DataMigration.java, components/patient-measurements/migrations/src/main/java/org/phenotips/measurements/internal/R54691PhenoTips1428DataMigration.java, components/studies/migrations/src/main/java/org/phenotips/data/permissions/internal/R71492PhenoTips2592DataMigration.java, components/studies/migrations/src/main/java/org/phenotips/data/permissions/internal/R71493PhenoTips2504DataMigration.java
XWiki cache has to be flushed at the end of migrator to prevent loading documents from the cache rather than from database.
=> PT-4003: Empty PubMedID are found after PhenoTips 1.3.10 upgrade to 1.4.6

components/vocabularies/api/src/main/java/org/phenotips/vocabulary/internal/solr/AbstractOBOSolrVocabulary.java, components/vocabularies/chebi/api/src/test/java/org/phenotips/vocabulary/internal/solr/ChEBIOntologyTest.java, components/vocabularies/hpo/api/src/test/java/org/phenotips/vocabulary/internal/solr/HumanPhenotypeOntologyTest.java
=> PT-4002 (stable): Reindexing HPO fails when an HPO term has more than one single value type field

components/pedigree/resources/src/main/resources/pedigree/model/export.js
The webapp UI requires the testing method column to be set when the BRCA
mutation column has a value other than 0.
(committing on behalf of @buske)
=> Fix BOADICEA export format to work with BOADICEA web application

components/pedigree/resources/src/main/resources/pedigree/model/phenotipsJSON.js
The `life_status` field takes values other than "alive" and "deceased" in regular, unlinked family member node json representations. Perhaps it was meant to be a special pedigreeProperty, but as is this drops all other life status values, causing it to return to the default of "alive".
=> PT-4018: Pedigree node life status not loaded from saved JSON

components/pedigree/resources/src/main/resources/pedigree/view/nodeMenu.js
This broke because `document.selection` stopped working in IE11 (it's `undefined`).
My solution is to use a different way to check whether the browser is IE, and then to restore the cursor position if it had been saved (rather than checking the browser type again in the restore).
=> PT-4019 After any edits, cursor is placed to the very end of the comment box in IE11

components/pedigree/resources/src/main/resources/pedigree/view/personVisuals.js
@allasm helpfully suggested a quick fix for this: making the user-defined `comments` label be the last one displayed (i.e. changing the order of labels displayed). He suggested adding better error checking for the values returned by `getBBox()` as a long-term solution.
After taking a closer look, I decided to fix the `comments` label rendering behaviour. This seems to me like a more targeted fix, since it does not change UX behaviour (i.e. order of the labels) and fixes the bug that's really relevant here (i.e. that the user-defined `comments` label is rendered even when it's effectively empty). Better error-checking for the values returned by `getBBox()` could still be added as an improvement, but shouldn't really be necessary.
=> PT-4020 In the pedigree editor, cancer labels are sometimes vertically offset from the relevant individual

components/pedigree/resources/src/main/resources/pedigree/familyData.js, components/pedigree/resources/src/main/resources/pedigree/saveLoadEngine.js
In the current version, if you open the pedigree, it immediately alerts you to exactly that sensitive information that you might not want to see with the patient present:
In the PR version, it first displays a generic break-glass message, with options to continue, go to the record, or show the details:
If you click "Show details", it displays them below:
If you didn't provide any details, it doesn't show the button at all.
=> PT-3917: sensitive pedigree details are shown when the pedigree is opened
